### PR TITLE
Add LocalGzipTarget.

### PR DESCRIPTION
**Pull request by themalkolm**
It is more Windows friendly as does not require you to have gunzip installed on the target machine.

Sure, I understand that this duplicates luigi.format.Gzip logic. But this works better for us as doesn't require to install gunzip everywhere. Not sure if you want it, though.

So, what do you think?

### CODE REVIEW

**Comment by erikbern** [comment]
LGTM but don't we already have a format argument that lets you do gzip?

**Comment by themalkolm** [comment]
@erikbern 

>Sure, I understand that this duplicates luigi.format.Gzip logic. But this works better for us as doesn't require to install gunzip everywhere. Not sure if you want it, though.

**Comment by Tarrasch** [comment]
I don't know. Can you somehow squeeze this into `luigi.contrib`? It's not core functionality and really all non-core stuff should go there, even `luigi.hdfs` I think.

**Comment by erikbern** [comment]
Yeah good point, makes sense.

**Comment by themalkolm** [comment]
Nah, maybe in next life.

**Pull request closed without merging**
