### PR TITLE
Add RangeDaily

### PR DESCRIPTION
**Pull request by ulzha**

### CODE REVIEW

**Comment by ulzha** [comment]
Only the last three normal commits were intended:
    refactor out RangeBase (in preparation to reuse for RangeDaily) …     9e96c6e
    add RangeDaily …     9db341e
    tweak formatting so log output looks consistent with parameter serial… …     b004e4a
I don't know why all the mess keeps tagging along. Ballmer peak over, will sort out tomorrow.

**Comment by erikbern** [comment]
lgtm

**Comment by ulzha** [comment]
Wonder if squashing necessary? Squashing the addition into the refactor would make quite an incomprehensible overhaul. I guess I could've PR'ed the refactor separately first...

**Comment by erikbern** [comment]
I don't have strong feelings

**Pull request merged**
