### PR TITLE
Version 2.7.3

### PR DESCRIPTION
**Pull request by honnix**
## Description
Prepare for the next release.

### CODE REVIEW

**Comment by dlstadther** [comment]
Is there a new release schedule? Or event which causes you guys to initiate a release?

**Comment by honnix** [comment]
2.7.3 has been uploaded to pypi, and there is a draft being prepared right now. You should be able to read it I think. https://github.com/spotify/luigi/releases/tag/untagged-7b7143d52c5be8f8af21

**Comment by Tarrasch** [comment]
> Is there a new release schedule? Or event which causes you guys to initiate a release?

I'm curious too. But even if you just do it sporadically I think it's really great. Thanks!

**Comment by honnix** [comment]
Technically our squad still own Luigi although almost no contribution. We are back to the business of occasional release which largely depends on internal ask. :)

We will for sure be careful with major release and will make sure the main contributors and maintainers are involved in that case.

**Pull request merged**
