### PR TITLE
Documented way for starting Luigi tasks inside Python code

### PR DESCRIPTION
**Pull request by Gr1f0n6x**
## Description

Information about another existing way for starting Luigi tasks
## Motivation and Context
This way can be useful if user wants to get dynamic params from anywhere before start the task and pass them automatically

### CODE REVIEW

**Comment by Tarrasch** [comment]
Looks good:

 * Can you change the filename from "comman_line" to "running_luigi" or something?
 * Perhaps remove the class file code?
 * If you mention `run()` you should also mention `build` I think to be fair, and also link to the whole run interface code module.

**Comment by erikbern** [comment]
I don't think this is the right way to run tasks from inside Python. Why deal with the command line interface at all

**Comment by erikbern** [comment]
Look at `interface.build`: https://github.com/spotify/luigi/blob/master/luigi/interface.py#L251

We should probably document that somewhere

**Comment by Tarrasch** [comment]
Actually yes, looking at the code it seems it heeds quite strong warnings against using it (written by myself a long time ago).

**Comment by Gr1f0n6x** [comment]
Oh, yes, i had to document build, not run (as i see now). It's all because i use run method in my code despite on warnings about it

**Comment by dlstadther** [comment]
Any update here @Gr1f0n6x ?

**Comment by Gr1f0n6x** [comment]
@dlstadther yes, sorry for delay (a lot of work), i'll continue to work on this issue and try to finish another one (parameter visibility)

**Comment by Tarrasch** [comment]
Wow, what an improvement! Thanks!

**Pull request merged**
