### PR TITLE
tests: Fix intermittent failures

### PR DESCRIPTION
**Pull request by Tarrasch**
The actually tests that are fixed are those (that are not even disabled)
in remote_scheduler_test.py. But the errors are easily reproduceable by
increasing the number of DummyTasks and decreasing the default value of
ping_interval.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Want to review guys? @erikbern @gpoulin

**Comment by erikbern** [comment]
looks good to me. we could always replace the KeepAliveThread with some tornado-specific thing.

**Comment by Tarrasch** [comment]
> we could always replace the KeepAliveThread with some tornado-specific thing.

I'm not sure I understand what you're suggesting. Do you mean that we change in the testing/mocking code or that we change the KeepAliveThread class in `worker.py`?

**Comment by Tarrasch** [comment]
Merging, in hope of that this is what caused the extremely surprising errors in #1182

**Comment by erikbern** [comment]
was suggesting we change the keepalivethread to use tornado threads during tests

**Pull request merged**
