### PR TITLE
Simplify interface.py

### PR DESCRIPTION
**Pull request by Tarrasch**
Previous code had unnecessary OOP abstractions. Also there were
countless of unrelated occurrences of the method "run".

### CODE REVIEW

**Comment by Tarrasch** [comment]
Oh, and the reason there previously was `class Interface(object)` was probably that we once supported both optparse and argparse. See #1004

**Comment by erikbern** [comment]
LGTM but might be worth slowing down with the refactoring soon so that people have time to run it locally!

**Comment by Tarrasch** [comment]
Well, my intention is a to do a quite big re-factoring. I try to split up the commits to speed up my own development and make it much easier to review.

Most of the PRs I've sent don't change any of the public behavior (that's why I started off with a PR turning everything into private, so people don't get affected by my PRs on a daily basis :))

**Comment by erikbern** [comment]
ok haven't you been removing lots of functionality though?

**Comment by Tarrasch** [comment]
I meant that I removed (hide) the functionalities in #1154 and #1157. So commits like this one doesn't touch any of luigi's public API.

**Pull request merged**
