### PR TITLE
Fix the link to the parameters documentation in the workflows page.

### PR DESCRIPTION
**Pull request by jaidevd**

### CODE REVIEW

**Comment by Tarrasch** [comment]
Not sure why ALL builds break suddently.

**Comment by jaidevd** [comment]
@Tarrasch Seems to  be failing when building HTTPretty - this might be useful - https://github.com/gabrielfalcao/HTTPretty/issues/223

**Comment by Tarrasch** [comment]
Aha thanks, does it require any changes on our side @jaidevd?

**Comment by jaidevd** [comment]
Someone mentioned it on that ticket that everything works fine if `HTTPretty==0.8.8`. Is there a quick way to try this out?

**Comment by Tarrasch** [comment]
Thanks for parsing that thread for me @jaidevd. See #949

**Pull request merged**
