### PR TITLE
Cleaned up some parameter parsing & dynamic dependencies

### PR DESCRIPTION
**Pull request by erikbern**
Would be great to get your input @tommyengstrom – in particular I'm not sure about the `__main__` stuff you were doing in `load_task`

### CODE REVIEW

**Comment by Tarrasch** [comment]
Didn't you just start to remove the optparse stuff in #612? It's confusing that there still are traces of it.

**Comment by erikbern** [comment]
Yeah wasn't super consistent... but this one should be merged first. For the optparse PR I want to give it a few days to see if anyone has any issues. I probably have to rebase the optparse PR later.

**Comment by erikbern** [comment]
I can remove the first commit from this PR if you think it makes more sense? The two commits have very little with each other to do

**Comment by erikbern** [comment]
Added even more tests now. Fairly sure this PR works. Definitely simplifies a lot of code with dynamic dependencies.

In case you haven't noticed, I'm trying to refactor various stuff with `luigi.interface` and `luigi.parameter`. It's all entangled so I have to start in other places.

**Comment by Tarrasch** [comment]
Alright LGTM but porbably give @tommyengstrom a day or so to review. :)

**Comment by erikbern** [comment]
Not sure what's up with Travis, but it looks like it passed

**Comment by erikbern** [comment]
Also does dynamic dependencies not run on other workers? When I tried to run it with multiple workers it doesn't look like it's parallelizing the tasks. I remember talking about this but forgot what we concluded – is there a fundamental reason why you can't put a dynamic dependency on another worker?

**Pull request merged**
