### PR TITLE
Fixed issue where string is appended to bytes.

### PR DESCRIPTION
**Pull request by pkbauer**

### CODE REVIEW

**Comment by Tarrasch** [comment]
I would expect that you add:

 * An explanation when this happens
 * A test case or a motivation why this is hard to test.

Thanks. :)

**Comment by pkbauer** [comment]
When this happens:
It happens when I try to write to hdfs.

    def output(self):
        import datetime
        today = datetime.datetime.now()
        output_file_name = '{}/{}{}'.format(self.output_path,
                                            today.strftime("%y-%m-%d-%H-%M"), ".out")
        if bool(self.local_mode):
            return S3Target(output_file_name)
        else:
            return luigi.contrib.hdfs.HdfsTarget(output_file_name)

**Comment by Tarrasch** [comment]
I really don't get it from your example, there's no writing going on there. Can you just create a failing test case to show that this is not just an arbitrary change?

**Comment by toidi** [comment]
I guess it will be better to integrate
```
from __future__ import unicode_literals
```
to whole luigi sources or at least to PR.

**Comment by Tarrasch** [comment]
Closing as it's been stale for a while.

**Pull request closed without merging**
