### PR TITLE
add option to RemoteTarget to use sshpass

### PR DESCRIPTION
**Pull request by kutschkem**
add support for password-based SSH via sshpass

### CODE REVIEW

**Comment by erikbern** [comment]
Looks great but you need to fix style. Run "tox -e pep8" locally and resolve issues.

**Comment by Tarrasch** [comment]
Can you squash your commits please? Would also be nice if you capitalized your commit message :) (see http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)

**Comment by kutschkem** [comment]
Squashing done

**Comment by erikbern** [comment]
merge conflict :(

**Comment by Tarrasch** [comment]
@kutschkem Awesome! Seems like you're not alone improving this file :)

**Comment by kutschkem** [comment]
Merge conflict resolved. Maybe someone should take the time to document all these options now that they are hidden in a **kwargs ;-)

**Comment by Tarrasch** [comment]
@kutschkem, yea maybe it shouldn't be a `**kwargs`, See discussion in #898`

**Pull request merged**
