### PR TITLE
put temp file into temporary directory and make it relative

### LINKED ISSUE #1368: FTP RemoteTarget tries to create local temp file in root
luigi.contrib.ftp.RemoteTarget open('r') tries to create a local temporary file based on the remote file path with a random suffix but using the entire path of the remote file.

In my case, the remote file is in the root folder of the FTP server so it tries to create the same file locally with '-luigi-tmp-%09d' as a suffix.  Because I don't have write permission to my root folder it fails.

### PR DESCRIPTION
**Pull request by a86c6f7964**
fixes #1368

### CODE REVIEW

**Comment by erikbern** [comment]
great. btw I have some ideas on how to refactor the temp file stuff, but will do separately

**Comment by Tarrasch** [comment]
This definitely needs a test case documenting the behaviour. I'm intending to refactor and generalize  this eventually, and I don't want this to break then =)

**Comment by a86c6f7964** [comment]
I assumed there is already a test case making sure that a file is written.

**Comment by Tarrasch** [comment]
The purpose of the test would be to make sure that if the implementation change is reverted, the test fails.

**Comment by a86c6f7964** [comment]
I fixed the existing test case to work, but it is an integration test with an ftp server (not my favorite). Then I added a line to make sure that the file can be opened and read properly. I do not think that the actual location that the file is put should be considered part of the test, but since the file is at an absolute location the test cannot pass since most machines do not let you write into /test/ directory location. (open to suggestions on a better way to test this)

**Comment by erikbern** [comment]
Can you resolve the flake8 errors?
```
./luigi/contrib/ftp.py:118:30: E261 at least two spaces before inline comment
./luigi/contrib/ftp.py:124:24: E261 at least two spaces before inline comment
./test/_test_ftp.py:191:66: E261 at least two spaces before inline comment
```

**Comment by a86c6f7964** [comment]
okay.

**Comment by erikbern** [comment]
you put the space in the wrong place :) should be before the # not after :)

**Comment by erikbern** [comment]
fyi you can run the tests locally by running `tox -e flake8`

**Comment by a86c6f7964** [comment]
oops. sorry about that. thanks for the tip. they look good now.

**Comment by erikbern** [comment]
thanks. will merge on travis!

**Pull request merged**
