### PR TITLE
enhanced examples documentation

### PR DESCRIPTION
**Pull request by steenzout**
* added coding statement where it was missing
* added license where it was missing
* added docstring documentation with details that should make it easy to decipher what is going on

I used my current understanding to add the details and finally managed to understand some of the "magic" under the hood but it's not perfect so there may be a few mistakes.

I think that some examples would be easier to understand if there were some diagrams.
I think this would mean adding them to the sphinx docs.
I can help with this if it's worthwhile or needed.

### CODE REVIEW

**Comment by themalkolm** [comment]
So I have no clue and want to ask a question. You just granted Spotify copyrights for all files by default. Are you sure all of them belong to Spotify? From my understating (I'm not a lawyer, though)  something in this repo could be contributed to project by other peoples under Apache License but this does not implies copyright to Spotify.

**Comment by erikbern** [comment]
I tend to agree that some of the docs is taking it a bit too far – we don't need to autogenerate html docs from examples, the point is to read them as they are. I might remove some of the more excecessive stuff

**Comment by erikbern** [comment]
afaik, you need to explicitly assign copyright to something, then grant permission for other people to use it

if you don't assign copyright, then the default assumption is anyone else is not permitted to use it

**Comment by steenzout** [comment]
@themalkolm I've raised this question before regarding the copyright notice.

I've finished my research and from what I'm seeing a project should have a Contributor License Agreement and a Corporate Contributor License Agreement.

a short article : http://oss-watch.ac.uk/resources/cla

a website to help understand CLAs more in-depth and has templates : http://harmonyagreements.org
(Canonical and others used this to generate their CLAs)

a beta tool that integrates with GitHub: https://www.clahub.com
I've tested this with an organization I own and it seems to work ok.

**Pull request merged**
