### PR TITLE
Fail build if docs are broken.

### PR DESCRIPTION
**Pull request by themalkolm**

### CODE REVIEW

**Comment by erikbern** [comment]
I think it's already failing? I saw a failing doc test earlier today :)

**Comment by themalkolm** [comment]
Do we generate docs in some other script?

**Comment by erikbern** [comment]
If you check out the latest builds on Travis, there's already a "docs" target: https://travis-ci.org/spotify/luigi

**Comment by themalkolm** [comment]
You are aware that this is my pull request, right?

**Comment by themalkolm** [comment]
This way you can locally run all tests by hitting `tox`.

**Comment by themalkolm** [comment]
But sure, commit message is invalid and I'm not going there.

**Pull request closed without merging**
