### PR TITLE
Add google-auth-httplib2 as dependency

### PR DESCRIPTION
**Pull request by honnix**
## Description

Adding a new dependency.
## Motivation and Context

As discussed here https://github.com/spotify/luigi/pull/2361#issuecomment-378661375

This is used by https://github.com/google/google-api-python-client/blob/v1.6.6/googleapiclient/discovery.py#L371

Another option is to fix `luigi.contrib.bigquery` somehow.
## Have you tested this? If so, how?
 

Manually installing this package worked for me.

### CODE REVIEW

**Comment by ulzha** [comment]
tox.ini is just adding it as a dependency for tests; didn't you mean to add it as a dependency for the real thing?

It's a bit unfortunate that contrib modules aren't separate packages with their own `setup.py`s; that would be the place to declare dependencies...

**Comment by honnix** [comment]
I did mean to put it as real thing. Sorry for the mistake. Another PR coming.

**Comment by honnix** [comment]
Now the problem is, I don't know where to put it. `setup.py` doesn't seem to be a good place. @ulzha as you mentioned, how do we handle contrib deps?

**Comment by honnix** [comment]
That looks like a big change in code structure. Not so sure we want to spend that much effort atm.

**Pull request merged**
