### PR TITLE
added chicken param to remove methods, consistent apis

### PR DESCRIPTION
**Pull request by coderfi**
such as mkdir and remove

### CODE REVIEW

**Comment by coderfi** [comment]
This is the follow up to my epic fail of a Pull Request #628 (which was also a fail for Pull Request #615).

Thanks for your help!

-Fi

**Comment by Tarrasch** [comment]
Can you make Travis happy? :)

**Comment by erikbern** [comment]
Can you also add some tests?

**Comment by coderfi** [comment]
Sure. I'll move the doctests out to somewhere your test harness can find.

Fi

**Comment by MartinXu** [comment]
can we have a  quick start  or detailed install doc for new user?

**Comment by Tarrasch** [comment]
@MartinXu Do you mean in general or for this particular Pull Request???

**Pull request closed without merging**
