### PR TITLE
Make DateHourParameter subclass of DateParameter

### PR DESCRIPTION
**Pull request by Tarrasch**
In addition to saving a few lines of code. It also prepares for even
more code reuse.

Also removed ancient TODO from 2012:
https://github.com/spotify/luigi/commit/f65d4cac9d4d867a696df6d3f7f1a95c709de276

### CODE REVIEW

**Comment by Tarrasch** [comment]
partially needed for #1091 like endeavours.

**Comment by sisidra** [comment]
DateParameter create datetime.date instance. Date(Hour/Minute)Parameter creates datetime.datetime instance.
Semantically those should not be subclasses imo.
If you invent DatetimeParameterBase for all of those 3, it would look much better.

**Comment by erikbern** [comment]
Yeah +1 for base class instead.

It's a classical OOP problem. Is a more-specified class a subclass of a less-specified class. Or the other way around? :)

**Comment by Tarrasch** [comment]
Haha, damn smart people like you never let me take shortcuts.

I'll resubmit the proper PR. :)

**Comment by erikbern** [comment]
Hehe ok just to explain what I mean: one classical example is: if you have two classes `Square` and `Rectangle` – which one inherits from which? `Square` is a special instance of `Rectangle` but you could also argue that `Rectangle` extends `Square`. So both ways kinda makes sense

**Comment by erikbern** [comment]
https://en.wikipedia.org/wiki/Circle-ellipse_problem :)

**Comment by Tarrasch** [comment]
Can you re review @erikbern @sisidra ?

**Comment by erikbern** [comment]
LGTM

**Pull request merged**
