### PR TITLE
Fix bytes/str confusion in luigi.contrib.sge

### PR DESCRIPTION
**Pull request by mivade**
This PR addresses #2215.

### CODE REVIEW

**Comment by sdhutchins** [comment]
Awesome. @mivade. I had been lazy and neglected all of the changes I made in that regard (I had to do this for a version I have working in a different project). If you want any help with the failed checks, I can help.

**Comment by mivade** [comment]
I'd be happy to add a test if someone has suggestions on how exactly to test this. Looking through the existing tests, it doesn't look like the affected code was ever actually tested in the first place. At any rate, there still appears to be something wrong because when I try to run a simple test task, I just get

```pytb
AttributeError: Can't get attribute 'SimpleTask' on <module '__main__' from '/home1/depalati/src/luigi/luigi/contrib/sge_runner.py'
```

**Comment by dlstadther** [comment]
I have no experience with sge so i'm just going to tag the various contributors to this package :)

@brcopeland @ivannotes and @jfeala

**Comment by leonqli** [comment]
> I'd be happy to add a test if someone has suggestions on how exactly to test this. Looking through the existing tests, it doesn't look like the affected code was ever actually tested in the first place. At any rate, there still appears to be something wrong because when I try to run a simple test task, I just get
> 
> ```
> AttributeError: Can't get attribute 'SimpleTask' on <module '__main__' from '/home1/depalati/src/luigi/luigi/contrib/sge_runner.py'
> ```
> 
> and despite this, luigi thinks that everything ran correctly.

How is the latest status? I still have the same issue...

**Comment by mivade** [comment]
I'm no longer working with SGE and never got feedback on what kinds of tests should be added. I'll leave this open until someone takes it over or submits a new PR.

**Pull request closed without merging**
