### PR TITLE
Remove optparse support

### PR DESCRIPTION
**Pull request by Tarrasch**
Since argparse is included in python >= 2.7, we don't add any
dependencies by adding this.

Trying to not break old code that much by allowing `use_optparse` to be
passed, but it will only be ignored and not affect anything.

### CODE REVIEW

**Comment by erikbern** [comment]
We should break if use_optparse is passed – the interfaces are not compatible with each other. Let's throw an exception and say that it's removed.

**Comment by erikbern** [comment]
other than that LGTM

**Comment by Tarrasch** [comment]
Is the only difference that ArgParseInterface assumes `task == argv[0]` but OptParseInterface has the `--task TaskA` syntax? Maybe we could make ArgParse accept both so we don't break old code? Also was there a reason the explicit `--task` was removed?

**Comment by erikbern** [comment]
the optparse interface doesn't have subcommands so we also register all parameters in a big unordered mess. so it's a bit messy

**Comment by Tarrasch** [comment]
Ah I see

**Comment by Tarrasch** [comment]
Closed in favor of #1036

**Pull request closed without merging**
