### PR TITLE
Remove some old/deprecated stuff from interface

### PR DESCRIPTION
**Pull request by erikbern**
- Removed optparse interface (I doubt anyone was using it – we had to use it at Spotify because of legacy reasons)
- Removed the "lock" parameter that's been deprecated for a long time

This is to prepare for a big parameter refactoring I have in another branch. It will be much easier to refactor if I don't have to support optparse. I'm not sure if anyone uses it, but please speak up if you do!

### CODE REVIEW

**Comment by Tarrasch** [comment]
Hooray for red diffs! :)

**Comment by erikbern** [comment]
I'll merge this in a day or two unless anyone objects

**Comment by erikbern** [comment]
Elias pointed out that Spotify still uses optparse in a bunch of places so I'll close this one

**Comment by Tarrasch** [comment]
Can we still remove the --lock arg?

**Comment by erikbern** [comment]
yeah i can resubmit that commit separately

**Pull request closed without merging**
