### PR TITLE
Add port kwarg to RemoteTarget.

### LINKED ISSUE #876: specifying ssh port for RemoteTarget
It would be nice to be able to specify a port number when establishing a RemoteTarget.

### PR DESCRIPTION
**Pull request by themalkolm**
Allow user to specify a custom port for ssh connections. Sometimes
people do expose ssh on other ports.

Fix #876

### CODE REVIEW

**Comment by Tarrasch** [comment]
No tests? :)

**Comment by themalkolm** [comment]
Do you run `test_ssh.py` automatically with a valid ssh endpoint? From my understanding - no. So what is the point for writing tests there?

**Comment by erikbern** [comment]
There are some tests, but they just rely on popen patching. We should have a real test to your point.

You would get marginally higher test coverage (2 extra lines) for just adding a port argument to the ssh tests though. But no biggie.

**Comment by themalkolm** [comment]
I am lazy today :)

**Comment by gpoulin** [comment]
We do have test with a real ssh [end point](https://github.com/spotify/luigi/blob/master/test/contrib/test_ssh.py#L33). On Travis we configure a [loopback](https://github.com/spotify/luigi/blob/master/.travis.yml#L35) to run those. I might be possible to change the default port.

**Comment by themalkolm** [comment]
Great! Maybe future-me will write tests some day!

**Pull request merged**
