### PR TITLE
Add missing kwargs passing for S3 multipart upload

### PR DESCRIPTION
**Pull request by jpiper**
Missed this one the first time around. Caused me a massive headache today!

### CODE REVIEW

**Comment by erikbern** [comment]
lgtm!

**Comment by erikbern** [comment]
next time plz add tests

**Comment by jpiper** [comment]
Hmm, for some reason the new phantomjs tests have failed here.

**Comment by erikbern** [comment]
rerunning the tests. maybe flakiness that we should fix separately

**Pull request merged**
