### PR TITLE
Unexport parameters stuff

### PR DESCRIPTION
**Pull request by Tarrasch**
The most of the content is in the second commit. Please see the commit message there.

@erikbern can you review as you wrote much of this?

For later when I actually refactor the code, I know have a rough idea of how many test cases that needs to be changed with that refactoring.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Also, by hiding the stuff now, it's unblocking a potential 2.0.0 release and the actual refactoring can happen under the hood not requiring yet another major version bump.

**Comment by erikbern** [comment]
LGTM

**Comment by jkukul** [comment]
@Tarrasch - this PR removed some public apis from `Parameter` class, e.g. `value`, `has_value`, `reset_global`, etc. For people who access them in workflows, upgrading from `1.3` to `2.0.0` will break things.  
 
I guess it's ok, since it's a major upgrade, but it would have been nicer if these methods were deprecated in one of `1.*` releases (just something to maybe keep in mind for the future).

**Comment by Tarrasch** [comment]
@jkukul - Then the cost for the maintainers is higher. I agree it would be nicer with deprecations in-between, but then we wouldn't have time to do other nice things. Also, *all of those methods were inherently buggy*. Their behaviour was undefined really.

I'm sorry if things broke for you. :-/

**Comment by Tarrasch** [comment]
Also this PR is related to #1182

**Comment by jkukul** [comment]
@Tarrasch no problem! I completely understand that the development speed is on the other side of the trade-off and that finding the right balance is hard.

**Pull request merged**
