### PR TITLE
Pin jinja2 version; >3.1 breaks sphinx build

### PR DESCRIPTION
**Pull request by dlstadther**
## Description

Pin jinja2 version to avoid error

## Motivation and Context

Related to https://github.com/readthedocs/readthedocs.org/issues/9037

`doc` build failure prevents merge of PRs

## Have you tested this? If so, how?
 

Local doc test and build is passing. Checking remote Github Actions now through PR

### CODE REVIEW

**Comment by dlstadther** [comment]
@sonjaer @honnix @ckiosidis @jesperps Could i get an approval here? Currently Github Action tests against master are failing. This resolves them. And i'd like to be able to merge code again with a passing build.

**Comment by dlstadther** [comment]
Hey @honnix , any chance you can help me out here? Or point me to the right path to identifying an appropriate Spotify employee or Luigi maintainer which i can catch up with?

I realize [as Spotify transitions away from Luigi use internally towards Flyte](https://engineering.atspotify.com/2022/03/why-we-switched-our-data-orchestration-service/), it will continue to be harder to get Spotify employee attention to this project. Have there been an internal conversation around Luigi support throughout this time?

**Review by rjcortese — APPROVED** [review]

**Comment by dlstadther** [comment]
@erikbern , I know you haven't been involved in Luigi in some time, but do you know the best contact within Spotify to help steer the project such that it'll continue to be (minimally) supported although Spotify is moving away from its use?

I may not be doing much here, but still at least trying to keep `master` decent. However, I can't merge bugfixes by myself.

**Review by honnix — APPROVED** [review]

**Comment by honnix** [comment]
> Hey @honnix , any chance you can help me out here? Or point me to the right path to identifying an appropriate Spotify employee or Luigi maintainer which i can catch up with?
> 
> I realize [as Spotify transitions away from Luigi use internally towards Flyte](https://engineering.atspotify.com/2022/03/why-we-switched-our-data-orchestration-service/), it will continue to be harder to get Spotify employee attention to this project. Have there been an internal conversation around Luigi support throughout this time?

Sorry I missed the comments. I have not worked very closely with the team but I will let them know. I understand your work load and frustration. We will see how we can make it better.

**Pull request merged**
