### PR TITLE
tests: Refactor (and actually test) server tests

### PR DESCRIPTION
**Pull request by Tarrasch**
This commit contains:

 * Removal of pretty much redundant tests in rpc_test
 * Moved tests from bin_test.py to server_test.py, as they were rendered
   useless after the refactoring in spotify/luigi#1129, probably
   forgotten since they were put in their own file in the first place.
 * Added test case 'test_with_cmdline'
 * Don't use any "random port", always use port 8083. Randomness like
   that leads to intermittent and irreproducible test failures.
 * Add a sanity check in INETURLLibServerTest that the HAS_REQUESTS
   mocking actually is meaningful.
 * Other small cleanups

### CODE REVIEW

**Comment by Tarrasch** [comment]
Does this make sense to you @graingert?

By the way @graingert. The reason I started with this endeavour is that I noticed a super-weird behaviour since we merged #1129. I realized the "bug" yesterday, but I bisected my way down to your commit there. The thing is I want to test to run luigi tasks locally without `--local-scheduler`. I was used to just being able to `./bin/luigid` and then run `./bin/luigi MyTask` basically. However, after that patch I get

```
❯ ./bin/luigid                   
2015-09-13 14:23:02,021 luigi-interface[24927] INFO: Loaded []
2015-09-13 14:23:02,022 luigi.server[24927] INFO: No prior state file exists at /var/lib/luigi-server/state.pickle. Starting with clean slate
2015-09-13 14:23:02,023 luigi.server[24927] INFO: Scheduler starting up
2015-09-13 14:23:42,464 tornado.application[24927] ERROR: Uncaught exception GET /api/ping (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8082', method='GET', uri='/api/ping', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '141', 'Host': 'localhost:8082', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'python-requests/2.6.0 CPython/2.7.6 Linux/3.13.0-45-generic'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/home/arash/spotify/repos/luigis/github_luigi/luigi/server.py", line 79, in get
    result = getattr(self._scheduler, method)(**arguments)
  File "/home/arash/spotify/repos/luigis/github_luigi/luigi/scheduler.py", line 811, in ping
    worker_id = kwargs['worker']
KeyError: 'worker'
2015-09-13 14:23:42,464 tornado.access[24927] ERROR: 500 GET /api/ping (127.0.0.1) 1.11ms
```

I spent hours tracking down the cause. I reached to the conclusion that it works if I do:

```
❯ /home/arash/spotify/repos/luigis/github_luigi/.tox/py27-nonhdfs/bin/python bin/luigid
2015-09-13 14:25:50,922 luigi-interface[25114] INFO: Loaded []
2015-09-13 14:25:50,923 luigi.server[25114] INFO: No prior state file exists at /var/lib/luigi-server/state.pickle. Starting with clean slate
2015-09-13 14:25:50,924 luigi.server[25114] INFO: Scheduler starting up
2015-09-13 14:26:18,842 tornado.access[25114] INFO: 200 GET /api/ping (127.0.0.1) 1.32ms
2015-09-13 14:26:19,846 tornado.access[25114] INFO: 200 GET /api/add_task (127.0.0.1) 2.03ms
2015-09-13 14:26:19,850 tornado.access[25114] INFO: 200 GET /api/ping (127.0.0.1) 1.20ms
2015-09-13 14:26:19,852 tornado.access[25114] INFO: 200 GET /api/add_task (127.0.0.1) 1.36ms
```

I checked that the python binaries match exactly. But they are assigned different `sys.path`s. Any ideas what could be wrong?

**Comment by erikbern** [comment]
These are now run in Travis?

**Comment by Tarrasch** [comment]
I didn't dare turn them on. As I don't think I've fixed that issue. We could do it and then revert it later. But maybe that commit can stay separate.

Naturally, I took extra care because of this and manually tested all the tests many times on py27 and py34.

**Comment by Tarrasch** [comment]
I assume you're fine with this change @erikbern. I'll continue to look into intermittent failures as I have time :)

**Pull request merged**
