### PR TITLE
MongoDB target items count

### PR DESCRIPTION
**Pull request by kritchie**
## Description
Added item count to the MongoDB target using aggregate method.
https://docs.mongodb.com/manual/reference/method/db.collection.count/#behavior

## Motivation and Context
I had a use case where I store data from a CSV file in a mongodb collection for later use. 
The CSV as a very specific number of lines and I don't need to redo the pre-processing each time I re-run the pipeline.

## Have you tested this? If so, how?
I ran my jobs with this code and it works for me.

### CODE REVIEW

**Comment by Tarrasch** [comment]
This PR is changing a module I don't know so much about. Can you do a `git blame` and look for other contributors who have edited those files and @-mention them to summon them as reviewers of this patch? Once others +1. I can help press "merge".

**Comment by kritchie** [comment]
Sure, looks like @MathiasDesch is the original contributor of this target. Mathias if you have a chance to look this up, would greatly appreciate !

**Comment by MathiasDesch** [comment]
Hi @kritchie,
the overall PR looks good to me. Just wondering  : 

Is there any specific reason to `return -1` if the collection does not exist?

I would rather see the logic of testing if the collection exists in charge of the client of this class. I feel that this task should only check the count and raise an exception if the collection is not present.

**Comment by kritchie** [comment]
Hi @MathiasDesch , thanks for taking time to look this up. 

The only reason I used the `return -1` was that when a collection doesn't exists, an exception would have been thrown, thus stopping the whole pipeline together because of that exception. This was unfortunate because my task was the one creating the said collection in the run method. So it was never going to be ran because of that. 

That being said, I get your point, it makes total sense. How about that, I will remove the check for the existence of the collection from the MongoCountTarget and I will add a new target in the file which would be a MongoCollectionTarget which would have the responsibility to verify if a collection exists or not. It would contain the logic to verify that a collection exists the same way I was doing it inside the MongoCountTarget.

With that new target I could add a prior task that will create the collection if it doesn't exist or simply skip if the collection already exists.

What do you think?

**Comment by MathiasDesch** [comment]
Perfect ! 👍

**Comment by kritchie** [comment]
@MathiasDesch I applied the changes and I've tested it with my tasks. It working fine on my side. If you can confirm on your side that would be awesome !

**Comment by MathiasDesch** [comment]
Everything looks good to me. @Tarrasch I think you can merge.
Thanks @kritchie !

**Pull request merged**
