### PR TITLE
Add OAO's name as a company which uses Luigi

### PR DESCRIPTION
**Pull request by henryrizzi**
## Description
Added OAO's name as a company which uses Luigi and linked to our site.

### CODE REVIEW

**Comment by erikbern** [comment]
Can you link to a presentation or something documenting your usage?

**Comment by Tarrasch** [comment]
Am I the only one getting a big warning trying to visit your companies webpage?

selection_083

**Comment by henryrizzi** [comment]
@erikbern I will try and find something documenting our usage. I don't think we have any links to our usage on the main corporate site, but we've been using Luigi for a lot of our newer ETL pipelines. :)
@Tarrasch I'm guessing it's getting flagged because the website might get caught by an advertiser filter or something along those lines. Ghostery doesn't complain to me, but I haven't used uBlock Origin before...

**Comment by Tarrasch** [comment]
@henryrizzi, cool, a link to any slidedeck website is also cool. :)

**Comment by dlstadther** [comment]
@henryrizzi Please rebase with latest changes and I'd be happy to merge your company into our list! Thanks!

**Comment by henryrizzi** [comment]
Oops. I think I messed up that rebase a bit. 😅

**Comment by Tarrasch** [comment]
Thanks. Conflict can now be resolved in GitHub UI :D

**Pull request merged**
