### PR TITLE
Fix error: AttributeError: 'Task' object has no attribute

### PR DESCRIPTION
**Pull request by Gr1f0n6x**
## Description

Add additional checks for attribute 'public_params' and method 'set_params'
## Motivation and Context

https://github.com/spotify/luigi/issues/2535
## Have you tested this? If so, how?
 

I have included unit tests for cases when scheduler tries to load old versioned tasks and make an attempt to accept new attribute or call new method.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Is this just to resolve an upgrade issue if you use pickled files? I'd rather not add this much complexity for that.

**Comment by Gr1f0n6x** [comment]
Yes, it's exactly for this purpose.  

When i've tried to resolve this I found a comment about pickling/unpickling old versioned files and that It can lead to issues like this. 
So, if this is ok than this PR can be closed.

**Comment by Tarrasch** [comment]
Backward compatibility would be nice if could be done in a much simpler and general way, and not unique to every kind of change we do to our representation of tasks.

Perhaps simply that the pickle file from now on has a version number, and we keep track of when we have to drop the file because the server can't support the file being loaded.

So I vote for closing this. Any other opinions?

**Comment by kwilcox** [comment]
I'd also vote on closing this (but thanks for the work!). Putting task representation changes in the CHANELOG and mentioning that pickle users will need to remove their old files will be more maintainable.

**Pull request closed without merging**
