### PR TITLE
Add http version of mortar help site back in to the docs

### PR DESCRIPTION
**Pull request by ddaniels888**

### CODE REVIEW

**Comment by erikbern** [comment]
I keep getting this error when i go there – I think you might have to change the subdomain or something?

image

**Comment by ddaniels888** [comment]
Hmm, I see that in Firefox but not in Chrome. I'll take a look.

**Comment by Tarrasch** [comment]
Hmm, works for me on Firefox

**Comment by ddaniels888** [comment]
I think this is an autofill feature in firefox, where if you've ever
visited the https version of a site it will force load https instead of
http, even if you type http. The url should be good; it's just the browser
that's being opinionated.

**Pull request merged**
