### PR TITLE
Use Codecov for uploading code coverage reports

### PR DESCRIPTION
**Pull request by stevepeak**
> Steve from Codecov here. I wanted to create this pull request to see if Luigi would like to use Codecov as their coverage solution.

Some of our core features include:

Some of our core features include:
- Seamless overlay of coverage reports in Github with our browser extensions. [Video](https://www.youtube.com/watch?v=d6wJKODB8_g)
- Awesome pull request comments. [Example](https://gist.github.com/codecov-io/ba612976215481e7f27c)
- Github commit status integration to ensure coverage meets minimum standards
- Automatic unified builds. See [pyca/cryptography](https://codecov.io/github/pyca/cryptography) for example
- Storing build environment variables.

View the report at https://codecov.io/github/stevepeak/luigi

Love all the feedback you have and I look forward to having Luigi on Codecov :)

Cheers,
Steve

### CODE REVIEW

**Comment by Tarrasch** [comment]
Looks cool. What do you @erikbern?

**Comment by erikbern** [comment]
I think coveralls is pretty crappy so let's take a look at this!

**Comment by Tarrasch** [comment]
Not sure I understand what it's showing in the browser. What are all the 1's in the left pane? For example here: https://codecov.io/github/stevepeak/luigi/examples/foo.py?ref=e4714696eee167a1811f7590f0d95417f4f17f9e

**Comment by stevepeak** [comment]
@Tarrasch there are a number of languages that support number of executed lines (I hope python in the near future as well). The 1's expresses execution count.

**Comment by Tarrasch** [comment]
Not sure if you can influence it. But can you remove that grey column for the python language then? :)

**Comment by stevepeak** [comment]
I can influence :+1: I think that can be arrange...when the data becomes available I'll add it. Thank you for the feedback.

**Comment by erikbern** [comment]
It's kind of random that test/contrib/hadoop_test.py is included but no other tests also. But other than that LGTM

**Comment by stevepeak** [comment]
You can ignore files in the Codecov UI. We process the `coverage.xml` file which included the test (not sure why not others).

Thanks!

**Comment by erikbern** [comment]
I changed my mind after trying to setting up Codecov for a bunch of other repos I have. Coveralls.io sucks but I wasn't even able to get Codecov working at all, which sucks even more.

Not sure if I want to advertise Codecov given my experience so I vote for closing this PR

**Comment by Tarrasch** [comment]
@erikbern, I think that because our tests do some weird stuff. When you run the hadoop tests it for some reason copies that file to the root. Never bothered to fix that, I think I just put it in my local gitignore...

**Comment by stevepeak** [comment]
@Tarrasch deployed the suggested change of removing number of hits in Python. Thank you!

**Comment by Tarrasch** [comment]
I'm good with merging. What do @ulzha and @econchick think?

**Pull request merged**
