### PR TITLE
History subsecond timestamp. Fixes #905

### LINKED ISSUE #905: Tasks that complete in <1s may display as RUNNING or PENDING in task history
Using MySQL backend, I am seeing tasks that have completed in either "RUNNING" or "PENDING" state in the task_history webpage.  Looking at the db there is a row marking these tasks as "DONE" but their timestamps clash with the displayed event.  Clearly the timestamps aren't sub-second precision.

E.g.

    mysql> select id, event_name, ts from task_events where task_id=61;
    +-----+------------+---------------------+
    | id  | event_name | ts                  |
    +-----+------------+---------------------+
    | 181 | PENDING    | 2015-04-22 15:10:02 |
    | 230 | RUNNING    | 2015-04-22 15:12:38 |
    | 231 | DONE       | 2015-04-22 15:12:38 |
    +-----+------------+---------------------+
    3 rows in set (0.00 sec)

Modern MySQL should support this.  I have found this stackoverflow question suggesting the issue is with SQLAlchemy: http://stackoverflow.com/questions/29711102/sqlalchemy-mysql-millisecond-or-microsecond-precision

Other than fixing this in SQLAlchemy it might work to simply sort task_event rows by timestamp *and* primary key, assuming the events are inserted in true order.

### PR DESCRIPTION
**Pull request by stephenpascoe**
Resubmitted PR after melding commits from #906.

Working-around lack of sub-second precision of MySQL timestamp.

### CODE REVIEW

**Comment by stephenpascoe** [comment]
This should be ready to merge now.  Travis is happy.

**Comment by Tarrasch** [comment]
Much better! I'll merge on a +1! :)

**Comment by gpoulin** [comment]
+1 :)

**Comment by Tarrasch** [comment]
Thanks @stephenpascoe ! :)

**Pull request merged**
