### PR TITLE
check for null and remove safety checks

### PR DESCRIPTION
**Pull request by coderfi**

### CODE REVIEW

**Comment by Tarrasch** [comment]
This PR contains too many orthogonal changes. Can you split this PR into a few smaller ones? I know the code size for each is small, but it's impossible to review this as it is now!

**Comment by Tarrasch** [comment]
Oh, and I think the code itself is overall good. So thank you and I'm looking forward to a few split up PRs. :)

**Comment by coderfi** [comment]
Good point. I'll see what I can do to split it up when I get the chance.

**Comment by erikbern** [comment]
Commit 3-4 LGTM but I'm not sure about 1-2

**Comment by erikbern** [comment]
but as @Tarrasch pointed out please break this up if possible

**Comment by coderfi** [comment]
Closing this request.
Opened up https://github.com/spotify/luigi/pull/628 (and possible others later), instead.
Thanks for entertaining this pull request!

-Fi

**Pull request closed without merging**
