### PR TITLE
Cleans up dangerous function default variables ([] and {})

### PR DESCRIPTION
**Pull request by sklarsa**
## Description
Changes function default variables `{}` -> `dict()` and `[]` -> `list()`

## Motivation and Context
Just cleaning up some of the errors from https://landscape.io/github/spotify/luigi/1347/messages/error

## Have you tested this? If so, how?
Ran `tox -e py27-nonhdfs` and everything passes

### CODE REVIEW

**Comment by dlstadther** [comment]
Thanks @sklarsa ! The errors here are waiting on #2274 for resolution

**Comment by sklarsa** [comment]
Sounds good.  Let me know if you need anything else from my end

**Comment by dlstadther** [comment]
Thanks @sklarsa !

**Comment by jhorman** [comment]
Is this still dangerous. The default args are still mutable. Isn't the right approach to set these to None, and default in code.

**Comment by kwilcox** [comment]
Correct @jhorman, this did not fix what was intended. However, I took a quick look and none of the mutable arguments are changed within the functions. It would be better to default these to `None` and set the defaults accordingly inside of the function as you mentioned but this shouldn't be causing any issues as is.

**Comment by Tarrasch** [comment]
@sklarsa, can you please send a new PR fixing this as @jhorman pointed out?

**Comment by sklarsa** [comment]
Yep I'll have one out this week

**Comment by sklarsa** [comment]
In `make_dataset` in `luigi/contrib/bigquery.py:177`, it appears that `body` is actually required since the first line of code assumes its existence and the `'id'` key... Not sure what to do here @mikekap?

**Pull request merged**
