### PR TITLE
Silence tests that fail intermittently

### PR DESCRIPTION
**Pull request by Tarrasch**
But we only silence the tests on Travis CI. Hoping for a balance between
productivity when merging PRs and that the tests actually get run
somewhere by someone.

### CODE REVIEW

**Comment by erikbern** [comment]
-1 we should fix underlying issues

**Comment by Tarrasch** [comment]
It has gone *too* long without the underlying issues being fixed. Nobody have prioritized it for too long. Still, every time I want to merge a PR, I need to manually waste minutes confirming that the failures are indeed just "intermittent" and then explain and excuse to new contributors who send PRs that we're "used" to these failures.

I don't have time right now to fix/find the underlying issues.

**Comment by erikbern** [comment]
ok sure, I buy that argument. I don't have time for a lot of things right now :(

**Comment by Tarrasch** [comment]
Make no mistake, it's with mixed feelings I'm pressing the merge button. :-/

**Pull request merged**
