### PR TITLE
Add Blendle to list of companies using Luigi

### PR DESCRIPTION
**Pull request by anneschuth**

### CODE REVIEW

**Comment by erikbern** [comment]
do you have a link to a presentation or something with more info?

**Comment by anneschuth** [comment]
Thanks @erikbern, it took us a while, but now we do have a presentation with more info, see http://www.anneschuth.nl/wp-content/uploads/sea-anneschuth-streamingblendle.pdf#page=126
Does this work for you? Also, I'm happy to make a new PR that isn't out of date if that'd be easier for you?

**Comment by Tarrasch** [comment]
New PR please as this seem to not be able to be merged from the browser. :)

**Comment by anneschuth** [comment]
Closing in favour of #1837.

**Pull request closed without merging**
