### PR TITLE
Fix parsing for TupleParameter

### LINKED ISSUE #2609: TupleParameter errors in dynamic dependencies
Passing a `TupleParameter` in a dynamic dependency results in a `TypeError` in Python 3.6.5. See the following example for a basic demonstration.

The following code:

```python
import luigi
import luigi.mock
import luigi.util

class FirstTask(luigi.Task):

    # my_tuple = luigi.ListParameter(default=(1, 2, 3))
    my_tuple = luigi.TupleParameter(default=(1, 2, 3))

    @property
    def tuple_string(self):
        return '-'.join(map(str, self.my_tuple))

    def run(self):
        print(self.task_id + ': ' + self.tuple_string)
        with self.output().open('w') as f:
            f.write(self.tuple_string)

    def output(self):
        return luigi.mock.MockTarget(self.task_id)


@luigi.util.inherits(FirstTask)
class SecondTask(luigi.Task):

    def run(self):
        input_target = yield FirstTask(my_tuple=tuple(self.my_tuple))

        with input_target.open('r') as src:
            my_tuple = src.read()
            print(self.task_id + ': ' + my_tuple)

            with self.output().open('w') as dst:
                dst.write(my_tuple)

    def output(self):
        return luigi.mock.MockTarget(self.task_id)

if __name__ == '__main__':
    luigi.build([SecondTask()], local_scheduler=True)
```

... results in this error:

```console
$ python scratch_9.py
DEBUG: Checking if SecondTask(my_tuple=[1, 2, 3]) is complete
INFO: Informed scheduler that task   SecondTask__1__2__3__a7a294ba13   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 10635] Worker Worker(salt=723375901, workers=1, host=DGJonathanDuckworth.local, username=jduckworth, pid=10635) running   SecondTask(my_tuple=[1, 2, 3])
INFO: [pid 10635] Worker Worker(salt=723375901, workers=1, host=DGJonathanDuckworth.local, username=jduckworth, pid=10635) new requirements      SecondTask(my_tuple=[1, 2, 3])
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Worker Worker(salt=723375901, workers=1, host=DGJonathanDuckworth.local, username=jduckworth, pid=10635) was stopped. Shutting down Keep-Alive thread
Traceback (most recent call last):
  File "/Users/jduckworth/Library/Preferences/PyCharmCE2018.3/scratches/scratch_9.py", line 40, in <module>
    luigi.build([SecondTask()], local_scheduler=True)
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/interface.py", line 274, in build
    return _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)['success']
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/interface.py", line 207, in _schedule_and_run
    success &= worker.run()
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/worker.py", line 1162, in run
    self._handle_next_task()
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/worker.py", line 1066, in _handle_next_task
    for module, name, params in new_requirements]
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/worker.py", line 1066, in <listcomp>
    for module, name, params in new_requirements]
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/task_register.py", line 253, in load_task
    return task_cls.from_str_params(params_str)
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/task.py", line 482, in from_str_params
    kwargs[param_name] = param.parse(param_str)
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/parameter.py", line 1107, in parse
    return tuple(tuple(x) for x in json.loads(x, object_pairs_hook=_FrozenOrderedDict))
  File "/Users/jduckworth/.virtualenvs/viper-dev/lib/python3.6/site-packages/luigi/parameter.py", line 1107, in <genexpr>
    return tuple(tuple(x) for x in json.loads(x, object_pairs_hook=_FrozenOrderedDict))
TypeError: 'int' object is not iterable
```

It looks like the problem is that the code [here](https://github.com/spotify/luigi/blob/master/luigi/parameter.py#L1117) catches a `ValueError`, but not a `TypeError`. I haven't tested in Python 2, but I'm assuming a `ValueError` gets thrown in that case and this is just a result of differences in Python versions.

I'm happy to put in a PR if it's helpful.

### PR DESCRIPTION
**Pull request by duckontheweb**
## Description

This fixes a bug in the parsing of `TupleParameters`, which led to uncaught errors in dynamic dependencies. 

## Motivation and Context
Fixes #2609 

## Have you tested this? If so, how?
I implemented this fix in a monkey patch within my project, and have also included a test for the desired fix.

### CODE REVIEW

**Comment by dlstadther** [comment]
Looks like `hypothesis[datetime]` was just [major version bumped](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/docs/changes.rst#400---2019-01-14) and removed the datetime package we were using (at least in the import path we were expecting). 

While we could update our code for this version 4.0.0, i'm going to suggest that for now we just update `tox.ini` to be `hypothesis[datetime]<4.0.0` since this is just used for some testing.

Any objection, @Tarrasch @honnix @ulzha ?

**Comment by dlstadther** [comment]
I fixed the above issue in #2622 

Please merge `master` into this branch so we can see the true Travis results :)

**Comment by duckontheweb** [comment]
@dlstadther Just merged those changes into this branch, but it looks like `flake8` is still failing (this is still the case for me locally as well).

**Comment by dlstadther** [comment]
```
./test/parameter_test.py:1108:1: E302 expected 2 blank lines, found 1
```

You just need to add another new line

**Comment by Tarrasch** [comment]
Can you give a clearer example (usage) on what problem this fixes?

**Comment by ktran9891** [comment]
@Tarrasch I can second this issue, which I have just found in my own pipeline.

I dropped down into the stack trace, and inside `TupleParameter.parse(self, '[1, 1, 1]')`, the `tuple(tuple(x) for x in json.loads('[1, 1, 1]', object_pairs_hook=_FrozenOrderedDict))` line raises a `TypeError`. But the method expects to a `ValueError`, and so the `TypeError` is uncaught and thrown. And just as @duckontheweb said, my parent task has dynamic dependencies.

I'd love for this PR to be merged!

**Comment by Tarrasch** [comment]
Sorry I forgot to look at the issue. It's all clear now. Thanks for this patch @duckontheweb  and thanks for chiming in @ktran9891.

**Pull request merged**
