### PR TITLE
Fix python 3.8 and 3.9 apache CI in dirty way

### PR DESCRIPTION
**Pull request by hirosassa**
## Description

Related to #3091 

I fixed Python 3.8 and 3.9 apache CI.
By [importlib change in Python 3.9.5 release](https://docs.python.org/release/3.9.5/whatsnew/changelog.html#core-and-builtins), `__import__()` returns absolute path of each modules or packages (this is relative path in previous version).
To maintain backward compatibility, I implemented dirty solutions (just rewrite absolute path into relative one).

I'd like to discuss my changes like [this](https://github.com/spotify/luigi/compare/master...hirosassa:fix-py38-py39-version-CI?expand=1#diff-db2f40c0e0465fa4e50b83de88558d5120ada69fa91cf60145e715e178d5a431R328) and find good solutions.

## Motivation and Context

To follow Python latest versions.

## Have you tested this? If so, how?
 

I ran test locally and GitHub Actions.

### CODE REVIEW

**Review by dlstadther — APPROVED** [review]
I've really fallen behind on reviews. I see that you've been keeping this branch up-to-date. I'm good with your solutions here for the sake of stable test builds. The path manipulation isn't ideal, but it allows better coverage against github actions' python versions 3.8 and 3.9. So i'll approve and merge.

Thanks for your patience and sorry again for my massive delays.

**Comment by hirosassa** [comment]
@dlstadther Thank you very much for the review!

**Comment by dlstadther** [comment]
Not sure what's up with the 2 tests that CI is waiting on. When i click into the Actions tab, i don't see those tests in the execution for this branch.

**Comment by hirosassa** [comment]
@dlstadther I disabled tests running on 3.8.9 and 3.9.4, and enabled 3.8 and 3.9 tests.
But the repository setting still requires 3.8.9 and 3.9.4 tests, so the tests are waiting on.
https://github.com/spotify/luigi/pull/3113/files#diff-7167d8d8ca9db60fcadbec1d7da1d3fe7fd300d6712810405f582a241d667c52L154-R156

**Comment by dlstadther** [comment]
Hmmm... Problem is that Github won't let me merge this PR until all tests return successful :/, including the two which are being replaced. Ideas?

**Comment by hirosassa** [comment]
@dlstadther 
It seems that we need to edit `Require status checks to pass before merging` settings in branch protection rules page (URL seems to be https://github.com/spotify/luigi/settings/branch_protection_rules/xxxxx).

**Comment by dlstadther** [comment]
Unfortunately, I don't have access to the repo's settings. I've only ever been a community member maintainer, never an admin or Spotify employee. So we may need one of the "dataex" members to help us out. @honnix @sonjaer @ckiosidis @jesperps

**Comment by dlstadther** [comment]
I looked at this a bit more and experimented, but came to the same conclusion as you @hirosassa . Without ability to modify those branch protection rules, we can't merge this :(

**Comment by hirosassa** [comment]
@narape How about you Nelson?

**Comment by honnix** [comment]
Sorry I missed the ping. I just updated the settings.

**Comment by hirosassa** [comment]
@honnix Thank you very much!

**Comment by dlstadther** [comment]
Thank you @honnix !

@hirosassa , feel free to update your branch with master and i'll merge once i see all greens! (no rush)

**Comment by hirosassa** [comment]
@dlstadther Updated! Thank you for your help!

**Pull request merged**
