### PR TITLE
Updated six to version 1.10.0

### PR DESCRIPTION
**Pull request by hudswideworld**
## Description
Updated six.py from v1.9.0 to v.1.10.0

## Motivation and Context

Six v.1.9.0 imports the _winreg module, which only works on Windows, and results in an ImportError when running on Linux machines. Six v.1.10.0 fixes that.

## Have you tested this? If so, how?
I have run my code and it works. I was only running into problems when I tried to use the pinject library, and this fixed my ImportError

### CODE REVIEW

**Comment by dlstadther** [comment]
resolves #1706

**Comment by dlstadther** [comment]
There are quite a number of newline additions. Did you modify the `six.py` module from Pypi, or is this the original?

**Comment by hudswideworld** [comment]
I did not modify anything. This should be the original

**Comment by Tarrasch** [comment]
Thanks!

**Pull request merged**
