### PR TITLE
Send kwargs to super in S3FlagTarget and GCSFlagTarget

### PR DESCRIPTION
**Pull request by bencharb**
Send kwargs to super in S3FlagTarget and GCSFlagTarget. Related issue: #946

### CODE REVIEW

**Comment by Tarrasch** [comment]
Red diffs! Awesome! :)

**Comment by bencharb** [comment]
Oops, I accidentally pushed additional commits to this pull request. It might be hard to back out of this now. Stand by.

**Comment by bencharb** [comment]
There are a few other related issues that prevent this from running correctly. I'll close this and resubmit another request via a branch when the other issues are solved.

**Comment by Tarrasch** [comment]
Cool. Thanks, reopen whenever you feel it's ready.

**Pull request closed without merging**
