### PR TITLE
Add Task for running Pig jobs.

### PR DESCRIPTION
**Pull request by jeremykarn**

### CODE REVIEW

**Comment by erikbern** [comment]
Nice! Is there any way this can be tested? Either by mocking or using the minicluster.

I think testing is optional for `luigi.contrib` but strongly encouraged :)

**Comment by Tarrasch** [comment]
Yep, tests would be nice. Also the last two commits should be amended . :)

Thanks for the patch!

**Comment by erikbern** [comment]
This is great! Minor thing is that the test should go into `test/contrib`. But let me merge this pull request (assuming the Travis build passes) and I will move the file using a direct commit

**Comment by jeremykarn** [comment]
Thanks!

**Pull request merged**
