### PR TITLE
Pull parameter default from config

### PR DESCRIPTION
**Pull request by erikbern**
Depends on #681

### CODE REVIEW

**Comment by erikbern** [comment]
Any thoughts?

**Comment by erikbern** [comment]
Can we merge this?

**Comment by ulzha** [comment]
Looks useful. I was thinking about this when arriving at the default values in Range stuff (kind of suited for our arbitrary situation and maybe unsuitable for others'): can have the hardcoded default overridable by a configured default, overridable by the dynamically specified value? Great if this does that; a test with both a hardcoded default and a configured value is lacking.

(Not sure of the usefulness of config_path, wonder why it was invented. Letting user come up with accidental complexity, namely mismatch between config section names and task names - for what purpose?)

**Comment by erikbern** [comment]
`config_path` is an artifact from before, now that they are pulled by default, we should probably deprecate `config_path`.

Let me add a couple of more tests then merge this.

**Pull request merged**
