### PR TITLE
Add Newsela to list of companies using Luigi

### PR DESCRIPTION
**Pull request by rayrrr**
We use Luigi at Newsela for ETL stuff, and we like it!

### CODE REVIEW

**Comment by Tarrasch** [comment]
We usually prefer links to slidedecks, presentations or blogposts. Do you have anything like that to link to instead of just to your website?

**Comment by rayrrr** [comment]
@Tarrasch not right now. We'd still like to be included on the list though, but it's up to you.

**Comment by dlstadther** [comment]
Hey @rayrrr, we've revamped how we record companies which use Luigi. We can accept your company into the list. Just resolve the conflict here and add your company to the list without extra luigi-related media. Thanks!

**Comment by dlstadther** [comment]
I'm not sure why this commit shows +6 instead of +1. But whatever. I'll merge after build turns green. Thanks

**Comment by rayrrr** [comment]
My mistake while resolving merge conflicts. It's +1 now. Build should pass :crossed_fingers: thanks!

**Comment by rayrrr** [comment]
At this point the build failure appears to be systemic:

```
Warning, treated as error:
README.rst:117: WARNING: Duplicate explicit target name: "spotify".
ERROR: InvocationError: '/home/travis/build/spotify/luigi/.tox/docs/bin/sphinx-build -W -b html -d /home/travis/build/spotify/luigi/.tox/docs/tmp/doctrees doc doc/_build/html'
___________________________________ summary ____________________________________
ERROR:   docs: commands failed
The command "./scripts/ci/conditional_tox.sh" exited with 1.
```

**Comment by dlstadther** [comment]
@rayrrr I keep seeing that error on multiple builds. Nothing you did.

I'm going to merge anyway as error is unrelated.

**Comment by dlstadther** [comment]
@Tarrasch something needs to be done about this build error. Also, the purpose of having these tests run is that they should be fast. However, the two `-cdh` builds alone take well over 30 minutes each to complete. What do they even test?

**Pull request merged**
