### PR TITLE
Support unix sockets for faster internal connections (MK II)

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by Tarrasch** [comment]
Thanks @graingert !

**Comment by Tarrasch** [comment]
When running the tests, don't you have the habit of doing "(a) try to ruin something in implementation (b) confirm that test fails now"? I'm still a bit worried that this could have happened.

**Comment by Tarrasch** [comment]
What's going on @graingert? Is this the first time you actually run the tests??? :s

**Comment by graingert** [comment]
I got them working with just requests, then backported the old code with a load of "refactors" on both the tests and code

**Pull request merged**
