### PR TITLE
Auto-run sphinx-apidoc

### PR DESCRIPTION
**Pull request by erikbern**
I don't really know how to test this with readthedocs, so I'll prob merge this and revert if it causes any issues

### CODE REVIEW

**Comment by erikbern** [comment]
Sorry for merging this without asking for more feedback. I don't know how to test-run things with readthedocs.

Fortunately, this time it actually works. It's so much nicer with all the submodules split up.

**Comment by erikbern** [comment]
Feel free to revert if you want to

**Comment by Tarrasch** [comment]
We're talking about this page right? http://luigi.readthedocs.org/en/latest/

**Comment by Tarrasch** [comment]
Yeah btw you can merge all you want for me atm.

**Comment by erikbern** [comment]
Yes http://luigi.readthedocs.org/en/latest/api/luigi.html

It's finally somewhat readable

**Pull request merged**
