### PR TITLE
ignore a "("

### PR DESCRIPTION
**Pull request by wwj718**
oh sorry ,  ignore a ")"

### CODE REVIEW

**Comment by Tarrasch** [comment]
Can you edit the commit message (just close this one and send a new one)? It's super confusing if you would do `git log` a year down the line. Maybe something like `Typo in docs: add a missing ")"`?

**Comment by Tarrasch** [comment]
But I really appreciate the PR! :)

**Comment by wwj718** [comment]
oh it is a good idea :smile:

**Comment by Tarrasch** [comment]
Please send a new PR with good commit msg. :)

**Comment by wwj718** [comment]
ok : )

**Pull request closed without merging**
