### PR TITLE
Add luigi.run() to task

### PR DESCRIPTION
**Pull request by harveyxia**
I needed to add these two lines to execute this task locally

### CODE REVIEW

**Comment by erikbern** [comment]
LGTM

**Comment by Tarrasch** [comment]
-1. I'm actually pushing for the `luigi --module example_top_artists AggregateArtists`. Approach, have you tried if that works @harveyxia ?

**Comment by harveyxia** [comment]
That doesn't seem to work for me. In any case, the README should be updated regarding the usage of 
```$ python examples/top_artists.py AggregateArtists --local-scheduler --date-interval 2012-06```, as currently the command doesn't execute the Luigi task

**Comment by erikbern** [comment]
yeah actually I'm with @Tarrasch now

**Comment by Tarrasch** [comment]
I tried to update the docs, can you verify that it work for you now @harveyxia? Sorry for the docs lagging behind. But feel free to fix it yourself too. :)

**Comment by Tarrasch** [comment]
Closing in favor of #1087

**Pull request closed without merging**
