### PR TITLE
Make the hard-timeout tests more forgiving

### PR DESCRIPTION
**Pull request by boosh**
Fixes #916

### CODE REVIEW

**Comment by Tarrasch** [comment]
Nice. Will merge once it's green :)

**Comment by boosh** [comment]
Thanks. @Tarrasch or @erikbern do you guys know when you're likely to release a new version of luigi?

**Comment by erikbern** [comment]
We can do that soon. There's a lot of minor fixes

**Comment by boosh** [comment]
OK great, thanks.

**Comment by boosh** [comment]
`export TOX_ENV=docs; export PYTHONPATH=''; tox -e $TOX_ENV`

This passes on my machine...

**Comment by Tarrasch** [comment]
Just a hiccup on that particular web page I guess. :)

**Pull request merged**
