### PR TITLE
Fix S3Client.remove - add max batch size

### PR DESCRIPTION
**Pull request by dlstadther**
Update `S3Client.remove()` to call `delete_objects()` on batches of 1000 (max).

## Description

[Boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.delete_objects) denotes that `delete_objects()` can be provided up to 1000 keys. We were passing it however many keys were in  `delete_key_list` with no maximum limit.

This patch implements a max of 1000 keys per batch to send to `delete_objects()`.

## Motivation and Context

Began receiving errors when attempting to recursively delete a lot of files with the following error message:
```shell
Runtime error:
Traceback (most recent call last):
  File "/opt/venv/local/lib/python2.7/site-packages/luigi/worker.py", line 205, in run
    new_deps = self._run_get_new_deps()
  File "/opt/venv/local/lib/python2.7/site-packages/luigi/worker.py", line 142, in _run_get_new_deps
    task_gen = self.task.run()
  File "/opt/luigi/my_file.py", line 1028, in run
   self.client.remove(self.prefix, recursive=True)
  File "/opt/venv/local/lib/python2.7/site-packages/luigi/contrib/s3.py", line 221, in remove
    self.s3.meta.client.delete_objects(Bucket=bucket, Delete={'Objects': delete_key_list})
  File "/opt/venv/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/venv/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (MalformedXML) when calling the DeleteObjects operation: The XML you provided was not well-formed or did not validate against our published schema
```
I then looked at boto3 documentation and found the 1000 key limit. Adding this patch's batching has prevented this MalformedXML error.

## Have you tested this? If so, how?
 

Existing tests refactored and new test added. (Was unable to force the error to occur with boto/moto)

### CODE REVIEW

**Comment by dlstadther** [comment]
@ouanixi Do you mind taking a look at this s3 PR as well?

**Comment by dlstadther** [comment]
It may also be worth noting that Boto3 integration tests [paginate their calls to `delete_objects()`](https://github.com/boto/boto3/blob/develop/tests/integration/test_s3.py#L83-L90)

**Comment by ouanixi** [comment]
Looks good to me. Worth checking there's not rate limit applied on these batch requests! Whether you're allowed to send as many batches of 1000s as you want kind of thing.

**Comment by dlstadther** [comment]
Anecdotally, I've been able to delete millions of files daily and not been rate limited yet.

https://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html

**Comment by dlstadther** [comment]
Given that boto3 doesn't do rate limit checking, i'm not concerned about adding that sort of logic here.

So i'm going to merge this bugfix through for next release once refreshed test suite finishes with a green build.

**Pull request merged**
