### PR TITLE
Fix postgres encoding with python2

### PR DESCRIPTION
**Pull request by gpoulin**
Fix #1062

### CODE REVIEW

**Comment by gpoulin** [comment]
@Tarrasch the current master is breaking Travis?

**Comment by Tarrasch** [comment]
Yea, I have no idea why that started to happening this Friday. I guess some library or something was released and the luigi package doesn't have proper upper bounds on its dependencies. I'll see if I can do something about this on Monday.

**Comment by erikbern** [comment]
This is much better – thanks!

**Comment by Tarrasch** [comment]
Oh, I forgot. Great thanks for you py2/3 and encoding ninja skills. I don't know what we would have done without you @gpoulin! :)

**Comment by tym-oao** [comment]
Thanks @gpoulin! :+1:

**Pull request merged**
