### PR TITLE
Add sqla to docs

### PR DESCRIPTION
**Pull request by gouthambs**

### CODE REVIEW

**Comment by Tarrasch** [comment]
LGTM

**Comment by erikbern** [comment]
nice

**Comment by erikbern** [comment]
http://luigi.readthedocs.org/en/latest/api/luigi.contrib.html#module-luigi.contrib.sqla

looks like there's some issue with formatting though. let me see if I can fix it

**Comment by erikbern** [comment]
fixed it

**Comment by gouthambs** [comment]
Thanks for fixing this. There is just the third example which seems broken.

**Comment by erikbern** [comment]
yeah there's also some weird doc generated for stuff from sqlalchemy. Let me see if I can remove it

**Comment by erikbern** [comment]
fixed the issue with the sqlalchemy stuff, the third example is still broken though :(

**Pull request merged**
