### PR TITLE
Fix db_task_import with python 3

### LINKED ISSUE #919: Failed to import 'db_task_history'
I tried enabling task history but it fails with:

    Traceback (most recent call last):
      File "/home/danderson/bin/luigid", line 9, in <module>
    load_entry_point('luigi==1.1.3', 'console_scripts', 'luigid')()
      File "/home/danderson/lib/python3.4/site-packages/luigi-1.1.3-py3.4.egg/luigi/cmdline.py", line 36, in luigid
    logdir=opts.logdir)
      File "/home/danderson/lib/python3.4/site-packages/luigi-1.1.3-py3.4.egg/luigi/process.py", line 117, in daemonize
    cmd(api_port=api_port, address=address)
      File "/home/danderson/lib/python3.4/site-packages/luigi-1.1.3-py3.4.egg/luigi/server.py", line 254, in run
    scheduler = CentralPlannerScheduler()
      File "/home/danderson/lib/python3.4/site-packages/luigi-1.1.3-py3.4.egg/luigi/scheduler.py", line 452, in __init__
    import db_task_history  # Needs sqlalchemy, thus imported here
    ImportError: No module named 'db_task_history'

I checked and db_task_history.py is where you would expect it to be

### PR DESCRIPTION
**Pull request by gpoulin**
Fix #919

### CODE REVIEW

**Comment by Tarrasch** [comment]
Thanks. Will merge once tests pass. (or let me know if this is urgent)

Why was this not detected by any of the tests?

**Comment by gpoulin** [comment]
@Tarrasch I think those lines are simply not cover, but coveralls is currently unavailable. We have tests for db_task_history but not for the 2 lines that import this module.

**Comment by Tarrasch** [comment]
Ah I see :)

**Comment by Tarrasch** [comment]
Enough tests pass for me, merging. :)



By the way @gpoulin, you have no clue about this guy do you?

```
======================================================================
ERROR: test_task_first_failure_time (rpc_test.RPCTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/spotify/luigi/.tox/py26-nonhdfs/lib/python2.6/site-packages/tornado/testing.py", line 120, in __call__
result = self.orig_method(*args, **kwargs)
File "/home/travis/build/spotify/luigi/test/central_planner_test.py", line 705, in test_task_first_failure_time
test_task = self.sch._state.get_task('A')
AttributeError: 'RemoteScheduler' object has no attribute '_state'
-------------------- >> begin captured logging << --------------------
tornado.access: INFO: 200 POST /api/add_task (127.0.0.1) 0.89ms
--------------------- >> end captured logging << ---------------------
```

**Comment by gpoulin** [comment]
@Tarrasch see my [comment](https://github.com/spotify/luigi/pull/916#issuecomment-97415559) in #916.

**Pull request merged**
