### PR TITLE
Map reduce format

### PR DESCRIPTION
**Pull request by stroykova**
Request: https://github.com/spotify/luigi/pull/1199
Was closed due to inactivity.

### CODE REVIEW

**Comment by erikbern** [comment]
LGTM but mapper should be lower case

**Comment by stroykova** [comment]
agree

**Comment by Tarrasch** [comment]
Can you amend the three commits?

**Comment by stroykova** [comment]
Amended.

Now I discovered that if reducer yields string, in the output we see letters joined by \t. Is it bug or feature?

**Comment by Tarrasch** [comment]
> Now I discovered that if reducer yields string, in the output we see letters joined by \t. Is it bug or feature?

I do not understand what you mean. It's not any code I'm comfortable with.

Is this otherwise ready to be merged?

**Comment by erikbern** [comment]
the key and value can be any type btw

**Comment by stroykova** [comment]
@erikbern thank you, I will add this explanation.
Question is about reducer. Looks like it also is expected to yield tuple. Unlike mapper and combiner it can have any length.

This thing about reducer is something to decide in architecture. I do not think it is expected string to become '\t' joined letters in output.

**Comment by Tarrasch** [comment]
Can you give an example of what you mean with '\t' joined?

**Comment by erikbern** [comment]
the '\t' is needed for hadoop streaming because it expects tab separated key/values

Luigi uses repr on top of that to represent objects (sorry, I said pickle, but I meant repr)

**Comment by stroykova** [comment]
I mean this:

```Python
def reducer(key, values):
    count = sum(1 for _ in values)
    yield key
```

Input:
("my_key", (1, 2, 3))

Output:
"m\ty\t_\tk\te\ty"

So I think I should also add info about reducer. Reducer is expected to yield tuples of any length.

**Pull request merged**
