### PR TITLE
Various Execution Summary fixes

### PR DESCRIPTION
**Pull request by Tarrasch**
A mix of cleanups and bugfixes. See the individual commits.

Thanks to @daveFNbuck for reporting the "printing own worker" bug in #1192.

### CODE REVIEW

**Comment by toidi** [comment]
+1 for `RunOnceTask`

**Comment by Tarrasch** [comment]
Does the rest of the patch look sane too @toidi ? :)

**Comment by Tarrasch** [comment]
Thanks for your hint @toidi, I made the diff (the last commit) even reder! :)

**Comment by erikbern** [comment]
great

**Pull request merged**
