### PR TITLE
Fix ListParameter Hashability

### PR DESCRIPTION
**Pull request by dlstadther**
## Description

With the merge of #2115, `ListParameter` normalization uses the `_recursively_freeze()` method to transform lists of dictionaries into tuples of `_FrozenOrderedDict`. However, `ListParameter`'s `parse()` and `serialize()` methods were not updated to utilize the `_DictParamEncoder`, allowing JSON serialization.

This PR resolves the serialization of lists of dictionaries provided to `ListParameter`.

## Motivation and Context

Fixes unhashability of `ListParameter` when provided a list of dictionaries caused by #2115.

## Have you tested this? If so, how?
 

Added hashability test for list of dictionaries.

### CODE REVIEW

**Comment by dlstadther** [comment]
@Tarrasch @j-ostrich Could y'all review? Thanks!

**Comment by j-ostrich** [comment]
I think the same changes should be made for `TupleParameter` since its members can also be objects. Other than that, LGTM.

**Comment by dlstadther** [comment]
`TupleParameter` and `ListParameter` only differ in their `parse()` methods. However, i'm not sure if it makes sense to subclass one of them as the other. Tuples and Lists are similar of use, but not in design or purpose.

Should I subclass `TupleParameter` as a class of `ListParameter`, only overriding the `parse()` method?

**Comment by j-ostrich** [comment]
I don't see the benefit of subclassing besides saving a couple of lines of code, but I'm also not against it.  LGTM, but I don't have write access so you'll have to wait for @Tarrasch to take a look.

**Comment by dlstadther** [comment]
@joemeszaros I see you added `DictParameter`. Do you think you could review this? It would be much appreciated! Then i'll merge.

**Comment by dlstadther** [comment]
I'll merge this tomorrow (2017-09-12) unless I hear otherwise.

**Comment by joemeszaros** [comment]
@dlstadther Sorry for the late response, but  I was on holiday and got back just now.

**Comment by dlstadther** [comment]
@joemeszaros No worries. Feel free to still review (although merged). If you have problems or suggestions, i'm happy to submit another PR with those changes.

**Pull request merged**
