### PR TITLE
Ensure DictParameter's are normalized to FrozenOrderedDict

### LINKED ISSUE #1657: Task finished yet the luigi failed.
I have py script contains the following task

class UpdateUserParameter(luigi.Task):
    udt = luigi.DateParameter()
    subject=luigi.Parameter()

    def output(self):
        return luigi.LocalTarget(local_proj_dir+'/data/crontab/{sub}/{dts}/is_user_parameter_updated.txt'.format(sub=self.subject, dts=self.udt.strftime('%Y-%m-%d')))
    def requires(self):
        return [users.UpdateUserParameterChain(subject=self.subject, udt=self.udt),
                users.UpdateUserKnowledgePointMasteryBuffer(subject=self.subject, udt=self.udt)
            ]

When the task runs, all task output is produced (including the master task) but the master task returns the following error:

Traceback (most recent call last):
  File "run_script.py", line 91, in <module>
    luigi.run()
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 210, in run
    return _run(*args, **kwargs)['success']
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 238, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 198, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 384, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 333, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 132, in _get_str
    params = _get_set_of_params(tasks)
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 173, in _get_set_of_params
    params[param] = {getattr(task, param[0]) for task in tasks}
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 173, in <setcomp>
    params[param] = {getattr(task, param[0]) for task in tasks}
TypeError: unhashable type: 'dict'

Because this error, other task depends on this cluster cannot be started. I cannot reliably reproduce this error and wonder how to fix it.

### PR DESCRIPTION
**Pull request by nugend**
## Description
I normalized dict parameters to instances of Frozen Ordered Dict's

## Motivation and Context
There was an outstanding bug

## Have you tested this? If so, how?
I have included unit tests

Closes #1657

### CODE REVIEW

**Comment by Tarrasch** [comment]
Can you fix the flake 8 issue? Otherwise this looks good :)

**Comment by Tarrasch** [comment]
Actually. Can you also add a test case to `parameter_test.py` as well? One day maybe we remove or move out the execution summary functionality, and it would be good if this property is still checked.

**Comment by nugend** [comment]
I've fixed the flake8 error.

After looking into the issue in more detail, this is not something that belongs in the parameter test cases. The only two places I can currently identify that this is an issue is in the execution summary and in the worker (where the worker checks if all the dependent tasks are complete and the inability to hash parameters causes, I *believe*, the lookup of the dependent task instances in the task registry to fail).

If you could help me figure out the best way to test this issue given that, I will add an additional test case in worker_test.py or another test module that you feel is appropriate.

Alternatively, this may be considered an issue with either worker or in how task_register handles its lookup. Honestly, I would consider the latter to be the case now that the task_id property is ostensibly a canonical string.

Regarding the flake8 error: Whenever I run `tox -e flake8` on my dev workstation, I see errors for contrib/ecs and contrib/salesforce which mean I don't get a green result. Is there a particular way I should be invoking flake8 to not trigger those? Or is it something about flake8 + Python 3.5?

**Comment by Tarrasch** [comment]
As for flake8, I have no idea. probably something with python 3.5. I hoped that tox would run exactly the same independent of platform, but it seems not. Oh well.

----

As for the additional test. I think you overcomplicate this. As I see it, hashability is a property for all parameters, so this situations simply warrants another simple test in `parameter_test.py`. That said, any added test case to any module would be greatly appreciated.

---

Lastly, finally we can push for merging in your range-related patch. :)

**Comment by nugend** [comment]
Ahhh, I did not realize that was intended to be a property of all Parameters.

I will add a corresponding simple test immediately. Should we also open an issue to add similar tests for other parameter types so as to ensure that this isn't an issue anywhere else? 

Also, is TaskParameter currently hashable?

**Comment by Tarrasch** [comment]
> Also, is TaskParameter currently hashable?

I think so, the reason I think so is that Range uses it, and there's not issue with combining Range with execution_summary (which apparently crashes when something isn't hashable)

**Pull request merged**
