### PR TITLE
Fixed: Rdbms and Redshift Properties

### PR DESCRIPTION
**Pull request by dlstadther**
Changed Rdbms' update_id to property. Appropriate changes made to Redshift.py and Postgres.py. Changed Redshift's do_truncate_table and queries to properties.

These changes were made to more accurately reflect their usage.

### CODE REVIEW

**Comment by dlstadther** [comment]
I don't understand why these errors exist. The affected files still produce the same output.

**Comment by dlstadther** [comment]
I screwed up my commits. I will fix and re-push.

**Comment by dlstadther** [comment]
...I keep screwing up the rebase. Can someone help guide me through the proper way to merge the new master into my branch without getting all the repeated commits?

**Comment by erikbern** [comment]
`git pull --rebase origin master` typically.

**Comment by erikbern** [comment]
or just `git rebase master`

**Comment by dlstadther** [comment]
I continue to mess this up. I'm going to close and reopen a new one with appropriate changes.... Sorry for my git incompetence.

**Pull request closed without merging**
