### PR TITLE
Fix of process lock on Windows

### PR DESCRIPTION
**Pull request by ngr-t**
The current version of
luigi.lock.getpcmd does not work properly on Windows, because Windows does not have ps command which is used to get command in the function. As a result, locking functionality does not work on Windows.
Fix the function to use wmic command instead of ps when luigi is run on Windows.

### CODE REVIEW

**Comment by erikbern** [comment]
After merging #1530 this has a merge conflict – would appreciate if you can rebase and resubmit! Thanks!

**Comment by ngr-t** [comment]
Thank you. I've done rebase and push (there seems to be conflicts, though...)
I didn't confirmed all tox tests pass, but "$ tox -e docs" passed.

**Comment by erikbern** [comment]
I think something went wrong when you rebased. Let me know if you can fix it. Alternatively if it's all messed up let me know and I can create a separate PR

**Comment by ngr-t** [comment]
I've fixed it.

**Comment by erikbern** [comment]
Something looks completely messed up. I think it's easier if you just restart from master and apply the change manually

**Comment by ngr-t** [comment]
Sorry.
I'll do as you suggested.

**Pull request closed without merging**
