### PR TITLE
fixes #2223 HdfsTarget is not workging with snakebite

### LINKED ISSUE #2223: HdfsTarget is not workging in luigi > 2.6.1
This code runs correct under luigi <= 2.6.1:

```python
from luigi.contrib import hdfs
import luigi.format

# just to be sure that realy the right version is used...
import pkg_resources
print "luigi ==", pkg_resources.get_distribution("luigi").version
print "snakebite ==", pkg_resources.get_distribution("snakebite").version

destination_file = '/tmp/test/file.gz'

target = hdfs.HdfsTarget(path=destination_file, format=luigi.format.Gzip)

if target.exists():
    target.remove(skip_trash=False)

fsobj = target.open('w')
fsobj.write('lol3\n')
fsobj.close()
```

with luigi 2.6.2 or 2.7.0 it breaks:
```python
luigi == 2.7.0
snakebite == 2.11.0
Traceback (most recent call last):
  File "/opt/tests/hdfs_target.py", line 18, in <module>
    fsobj.close()
  File "/opt/python-2.7.10/lib/python2.7/site-packages/luigi/format.py", line 224, in close
    self._output_pipe.close()
  File "/opt/python-2.7.10/lib/python2.7/site-packages/luigi/contrib/hdfs/format.py", line 51, in close
    remove(self.path)
  File "/opt/python-2.7.10/lib/python2.7/site-packages/luigi/contrib/hdfs/clients.py", line 62, in result
    return getattr(get_autoconfig_client(), method_name)(*args, **kwargs)
  File "/opt/python-2.7.10/lib/python2.7/site-packages/luigi/contrib/hdfs/snakebite_client.py", line 140, in remove
    return list(self.get_bite().delete(self.list_path(path), recurse=recursive))
  File "/opt/python-2.7.10/lib/python2.7/site-packages/snakebite/client.py", line 1540, in wrapped
    yield results.next()
  File "/opt/python-2.7.10/lib/python2.7/site-packages/snakebite/client.py", line 508, in delete
    for item in self._find_items(paths, processor, include_toplevel=True):
  File "/opt/python-2.7.10/lib/python2.7/site-packages/snakebite/client.py", line 1216, in _find_items
    raise FileNotFoundException("`%s': No such file or directory" % path)
snakebite.errors.FileNotFoundException: `/tmp/test/file.gz': No such file or directory
```

client.cfg:
```
[hdfs]
client = snakebite
snakebite_autoconfig = True
tmp_dir: /x/tmp
```

The file is correct in form and content written in "tmp_dir" (/x/tmp/username/test/file.gz-luigitemp-951771388).

### PR DESCRIPTION
**Pull request by zwotzie**
## Description

Full History you can find here: https://github.com/spotify/luigi/issues/2223

I only added the FileNotFoundException if you are using snakebite. The "old" code doesn't expect this, but in only one class behind in the same file it does.

## Motivation and Context
to update > 2.6.1 :)

## Have you tested this? If so, how?
yes of cause see Issue...

This change does not break anything, so i don't have added additional tests.

### CODE REVIEW

**Comment by dlstadther** [comment]
Is this not the same as https://github.com/spotify/luigi/pull/2549 ?

**Comment by zwotzie** [comment]
first i thought it would be the same and tested 2.8.0, but it is different. #2549 do not fix the problem with the upcomming exception from snakebite.

**Comment by zwotzie** [comment]
:)

**Comment by zwotzie** [comment]
Hi, is there a reason why this merge is not already integrated?

**Comment by zwotzie** [comment]
Hmmmm, nothing happen here for this easy change... It is a bit frustrating

**Comment by dlstadther** [comment]
@zwotzie Currently the tests against this branch are failing. I believe this is due to branching off a bad master. We prefer not to merge branching which have tests failing, even if the changes reflected in this PR aren't the cause of the test failures.

The master branch is currently passing. So could you please merge `master` into this branch so that we can evaluate Travis' test results? If all passes, i'll merge.

**Comment by zwotzie** [comment]
thanks for you advice. done :)

**Comment by dlstadther** [comment]
All tests pass! Appreciate it!

**Pull request merged**
