### PR TITLE
enable range use with luigi.rdbms.CopyToTable

### PR DESCRIPTION
**Pull request by ulzha**

### CODE REVIEW

**Comment by erikbern** [comment]
LGTM. Btw `luigi.postgres` has really bad test coverage, would be great to bump it up a bit

**Comment by Tarrasch** [comment]
LGTM

**Comment by ulzha** [comment]
Yeah, I was about to add more but gave up after figuring I lack knowledge of the best tools to test a database interface. One generic way would be just to use plain MagicMock and assert on the entire mock_calls list, but one needs to specify fetchone return values. I would hate to laboriously implement all sorts of mock cursors. There should be a quite trivial generic way to script all the important `side_effect`s inline with the definition of the expected calls list itself. But I couldn't google the magic quickly. Wonder if I should invent it?

**Comment by erikbern** [comment]
Yeah using MagicMocks is a bit messy.

I was also thinking about maybe just spin up a Postgres cluster locally or something, but it might be overkill

**Pull request merged**
