### PR TITLE
Add DJ/WSJ to list of companies.

### PR DESCRIPTION
**Pull request by jewer**
We've been using luigi at DJ/WSJ for about a year off/on but have started using it exclusively for all our pipeline coordination.  Love it!

### CODE REVIEW

**Comment by erikbern** [comment]
That's awesome! Would love it if you can provide some more info :)

**Comment by jewer** [comment]
Sure thing.  Anything specific at all?  Use cases or just a couple sentences?

**Comment by erikbern** [comment]
Was just curious what you use it for. I'm guessing data analytics on the web sites mostly?

**Comment by jewer** [comment]
We build a lot of predictive models for measuring user behavior and subscriber churn, so a lot of coordinating between Hadoop, BigQuery, and Spark jobs.   Mostly around web site traffic; hoping to explore more interesting first-party data instead of commodity web traffic data.

**Comment by erikbern** [comment]
cool!

**Pull request merged**
