### PR TITLE
Cleaned up temp_dir function in test/simulate (branch renamed)

### PR DESCRIPTION
**Pull request by Yoone**
Cleaned up test code from #1245.
Duplicate for #1275. Renamed the branch, just in case it's the reason Travis doesn't run the tests.

### CODE REVIEW

**Comment by Tarrasch** [comment]
It seem to run it now. Nice :)

**Comment by Tarrasch** [comment]
Thanks for the audit. But I hoped for you to be able to get rid of the `@is_writeable` decorator to. :)

**Comment by Yoone** [comment]
Oh but sadly the tests don't pass on `py27-nonhdfs` without it, and I really haven't found a better way.

**Comment by Tarrasch** [comment]
Hmm. OK

**Pull request merged**
