### PR TITLE
execution summary: Don't crash on uncomparables

### PR DESCRIPTION
**Pull request by Tarrasch**
This has become increasingly important since spotify/luigi#1479 where
EnumParameters have been introduced (which are normally not sortable)

### CODE REVIEW

**Comment by erikbern** [comment]
LGTM

**Comment by erikbern** [comment]
we need to fix flaky visualizer test

**Comment by jimjh** [comment]
thanks!

**Comment by Tarrasch** [comment]
@jimjh you're welcome :)

**Pull request merged**
