### PR TITLE
[DONTMERGE] Will travis fail now?

### PR DESCRIPTION
**Pull request by Tarrasch**
See #776

### CODE REVIEW

**Comment by Tarrasch** [comment]
Well it didn't fail only for the reasons I wanted. I'll continue on this tomorrow.

**Comment by berkerpeksag** [comment]
It worked actually:

```
Ran 470 tests in 35.960s
FAILED (errors=3)
ERROR: InvocationError: '/home/travis/build/spotify/luigi/.tox/nonhdfs/bin/python test/runtests.py -v'
___________________________________ summary ____________________________________
ERROR:   nonhdfs: commands failed
The command "tox -e $TOX_ENV" exited with 1.
```

**Comment by gpoulin** [comment]
@berkerpeksag It fails, but it's because other tests doesn't find server_test module https://travis-ci.org/spotify/luigi/jobs/51862320#L726. #782 actually fails for the right reason, there is a test that doesn't pass https://travis-ci.org/spotify/luigi/jobs/51936777#L753.

**Comment by Tarrasch** [comment]
Closing in favor of https://github.com/spotify/luigi/pull/782

**Pull request closed without merging**
