### PR TITLE
Remove the confusing "dummy_test_module" directory

### PR DESCRIPTION
**Pull request by Tarrasch**
## Description
Remove the confusing "dummy_test_module" directory

## Motivation and Context
The purpose is simply to remove a confusing module from the luigi root
directory. It was only used from tests but it couldn't be put in the
test module for whatever technical reasons.

## Have you tested this? If so, how?
This is only affecting tests. If tests pass it should be OK.

### CODE REVIEW

**Comment by Tarrasch** [comment]
@daveFNbuck, does this look sane to you?

**Comment by daveFNbuck** [comment]
I'm not sure it makes sense to import the unloaded module for the dynamic
loading test. I think importing it invalidates the test.

**Comment by Tarrasch** [comment]
> I'm not sure it makes sense to import the unloaded module for the dynamic loading test. I think importing it invalidates the test.

Not sure we're on the same page.

The helper creates a module (a file within our PYTHONPATH) *without* loading it. Later, we run `luigi --module that_yet_unloaded_module ...`, and see if luigi is actually loading it or not.

**Comment by daveFNbuck** [comment]
Sounds good.

**Pull request merged**
