### PR TITLE
Add ODBC target.

### PR DESCRIPTION
**Pull request by artiya4u**
Add ODBC target to support more RDBMS target like SqlServer, MySql, Oracle.
Using pyodbc library https://code.google.com/p/pyodbc/ .

### CODE REVIEW

**Comment by erikbern** [comment]
Looks great but please put it in `luigi.contrib.odbc` instead.

What's the difference from the existing database support? Can we have a unified interface?

**Comment by gpoulin** [comment]
Correct me if I'm wrong, but sqlalchemy support pyodbc. Wouldn't it be better to improve the sqlalchemy target? I should have some time in the following weeks to work on this. Personally, I would deprecate `luigi.contrib.mysql`, `luigi.postgres`, `luigi.contrib.rdbms` and some part of `luigi.contrib.redshift` and try to handle all those cases with sqlalchemy. Just a suggestion.

**Comment by Tarrasch** [comment]
If sqlalchemy covers all of them, then it makes sense to let that target rule them all, as long as it's proven to be stable. :)

**Comment by artiya4u** [comment]
@gpoulin Thanks for suggestion. I would look at sqlalchemy.

**Comment by Tarrasch** [comment]
Cool. Please contribute back your findings as well :)

**Pull request closed without merging**
