### PR TITLE
Add Python 3.7 compatibility

### PR DESCRIPTION
**Pull request by dlstadther**
## Description

Python 3.7.0 has been released. Time to check for Luigi compatibility.

## Motivation and Context

Let's try to keep up with most recent Python versions!

## Have you tested this? If so, how?
 

Letting Travis do this :)

### CODE REVIEW

**Comment by dlstadther** [comment]
If successful, will need to update README

**Comment by dlstadther** [comment]
At least one error is caused by: https://github.com/spulec/moto/issues/1706

**Comment by dlstadther** [comment]
With regard to the moto error, we'll need to update our moto version with the Python 3.7 compatible version.

We're currently testing against `moto<1.0`. Moto 1.0.0 [denotes breaking changes for decorators](https://github.com/spulec/moto/blob/master/CHANGELOG.md#100).

So an additional PR may need to be submitted to update our moto test dependency. I'll submit a naive WIP one to see how badly things break.

**Comment by dlstadther** [comment]
Thanks so much @dalejung ! I hadn't found the time to resolve the postgres issue. I've copied your build changes here.

**Comment by dalejung** [comment]
:+1: Had to wrangle with travis updating some personal libs. Happy the info was useful elsewhere.

**Comment by dlstadther** [comment]
@ulzha  How's this look to you?

At some point, we should probably do something about our test speed. We're now exceeding 30m to find out if everything passes. What are your (and @Tarrasch 's) thoughts on cutting down to Py2.7, 3.7 explicit support? I understand many people may be using 34/35/36, but testing `nonhdfs` for each gets resource hungry.

**Comment by honnix** [comment]
Hard decision, but 30m is way too much. I wish I could find some stats of which Python versions are more popular than the other. :/

**Comment by honnix** [comment]
I guess my above answer is not helping at all. :D How about we drop 34/35 first? Give 36 one more year?

**Comment by dlstadther** [comment]
I'd support dropping tests for 34/35. If we go that route, i'd suggest updating our README to denote previous support for those versions, but that they are no longer included in the the automated test suite.

**Comment by honnix** [comment]
Sound like a plan. Let's go for it. BTW, in readme we say 3.3 still, lol.

**Comment by dlstadther** [comment]
Cool. I push those changes here shortly. Then this will be good to merge. Thanks @honnix !

**Comment by honnix** [comment]
👍

**Comment by honnix** [comment]
Is this worth a minor version bump? I'm drafting and releasing `2.7.9` and this PR can go to `2.8.0` perhaps.

**Comment by dlstadther** [comment]
If we're dropping explicit (tested) support for Python versions, i'd say this deserves `2.8.0`.

Thanks for taking care of `2.7.9`!

**Comment by honnix** [comment]
:shipit:

**Pull request merged**
