### PR TITLE
Issue template: Mention it isn't for questions

### PR DESCRIPTION
**Pull request by Tarrasch**
Recently there have been many issues opened with user questions. And they sometimes can add to the maintainer burden.

------

Here are two issues I had in mind when proposing this change:

 * https://github.com/spotify/luigi/issues/2142
 * https://github.com/spotify/luigi/issues/2137

Hopefully with this patch we can save everyone's time.

### CODE REVIEW

**Comment by Tarrasch** [comment]
@dlstadther, Yes, but (1) some percentage of people will read it and (2) I don't need to feel bad closing issues. :)

**Comment by dlstadther** [comment]
@Tarrasch I'm fine to merge this (i'd do it myself, but Spotify bumped me off as an outside collaborator this morning)

**Comment by Tarrasch** [comment]
@dlstadther me too ;p, I'll try to reach out to them. I'd guess it's a mistake (or possibly an otherwise pretty sensible new policy).

**Comment by dlstadther** [comment]
Rebased and force-pushed to make Travis rebuild

**Comment by dlstadther** [comment]
I don't know why Travis won't run. But this PR doesn't affect Luigi, so i'm merging regardless

**Pull request merged**
