### PR TITLE
Log underlying RPC exception.

### PR DESCRIPTION
**Pull request by dhruvg**
Trying to get more visibility into `RPCError`... and it seems we don't log the underlying exception, thereby hiding the details which would be useful for debugging these.

```
HTTPError: 500 Server Error: Internal Server Error
Traceback (most recent call last):
  File "/apps/production/enterprise/current/enterprise/jobs/twitterads.py", line 55, in <module>
    luigi.run(main_task_cls=TwitterAdsBootstrap)
  File "/apps/production/enter
prise/virtualenvs/enterprise/local/lib/python2.7/site-packages/luigi/interface.py", line 331, in run
    return _schedule_and_run(tasks, worker_scheduler_factory)
  File "/apps/production/enterprise/virtualenvs/enterprise/local/lib/python2.7/site-packages/luigi/interface.py", line 184, in _schedule_and_run
    success &= w.run()
  File "/apps/production/enterprise/virtualenvs/enterprise/local/lib/python2.7/site-packages/luigi/worker.py", line 756, in run
    self._handle_next_task()
  File "/apps/production/enterprise/virtualenvs/enterprise/local/lib/python2.7/site-packages/luigi/worker.py", line 686, in _handle_next_task
    assistant=self._assistant)
  File "/apps/production/enterprise/virtualenvs/enterprise/local/lib/python2.7/site-packages/luigi/worker.py", line 359, in _add_task
    self._scheduler.add_task(*args, **kwargs)
  File "/apps/production/enterprise/virtualenvs/enterprise/local/lib/python2.7/site-packages/luigi/rpc.py", line 169, in add_task
    'assistant': assistant,
  File "/apps/production/
enterprise/virtualenvs/enterprise/local/lib/python2.7/site-packages/luigi/rpc.py", line 145, in _request
    page = self._fetch(url, body, log_exceptions, attempts)
  File "/apps/production/enterprise/virtualenvs/enterprise/local/lib/python2.7/site-packages/luigi/rpc.py", line 138, in _fetch
    last_exception
luigi.rpc.RPCError: Errors (3 attempts) when connecting to remote scheduler 'http://127.0.0.1:12300'
```

### CODE REVIEW

**Comment by Tarrasch** [comment]
I thought `logger.exception` already printed the stack trace in addition to the error message. No?

**Comment by dhruvg** [comment]
I think you're right. The underlying issue is the HTTP 500 error. Have you noticed this before? It seems sporadic, but I only started seeing this after upgrading `luigi` to master. I am able to access the scheduler on my browser, so not sure what is causing the 500.

**Comment by Tarrasch** [comment]
Could it be related to #1129?

Anyway I'm closing since this PR will just make it print 2 stack traces.

**Comment by Tarrasch** [comment]
Maybe @graingert might know something here, he's done lots of relevant PRs with the connection to the server: https://github.com/spotify/luigi/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Agraingert

**Comment by graingert** [comment]
@dhruvg the new version should raise the actual error that happened. You should be able to see in your luigid logs for the source of the 500 error

**Comment by dhruvg** [comment]
@graingert Fantastic, I found it. Thanks!

**Comment by graingert** [comment]
@dhruvg what did you find?

**Comment by dhruvg** [comment]
The source of the 500 was a `NoneType` error.

**Pull request closed without merging**
