### PR TITLE
Render documentation on separate pages

### PR DESCRIPTION
**Pull request by erikbern**
I hope this works – last time there were discrepancies between my local environment and readthedocs

### CODE REVIEW

**Comment by erikbern** [comment]
Also nice to remove 400 lines :)

**Comment by Tarrasch** [comment]
What will the difference be?

**Comment by erikbern** [comment]
Right now http://luigi.readthedocs.org/en/latest/api/luigi.html is one big page. This breaks it down into one page per submodule

**Comment by erikbern** [comment]
I'll try merging and if it doesn't work I'll revert

**Comment by erikbern** [comment]
Crap, readthedocs still does something weird. No idea what. I'll revert for now. Will see if there's a version mismatch

**Comment by berkerpeksag** [comment]
The reason is that readthedocs is not invoke `tox -e docs`. It invokes `sphinx-build` instead: http://docs.readthedocs.org/en/latest/builds.html#understanding-what-s-going-on

**Pull request merged**
