### PR TITLE
Add Klarismo to list of users

### PR DESCRIPTION
**Pull request by dewet22**
## Description

We are using Luigi in production to reliably process massive datasets of volumetric data.

### CODE REVIEW

**Comment by erikbern** [comment]
Can you link to a presentation or blog post or something where you talk about your Luigi use? Note that all most other links are that way. Thanks!

**Comment by dewet22** [comment]
We don't have anything public just yet, but I have an intention to write a post about how we're integrating Luigi with JIRA and Slack. Should I hold back until that's published, or can I just update the link later?

**Comment by erikbern** [comment]
We can keep the PR open until then so that you have more incentive to write the post :)

**Comment by erikbern** [comment]
can you rebase on latest changes now? thanks!

**Comment by dewet22** [comment]
Let's just close this for now.

**Pull request closed without merging**
