### PR TITLE
Environment variable to set the encoding of the configuration file.

### PR DESCRIPTION
**Pull request by mpoussevin**
Possible solution for the issue I opened : #2397 

## Description

I added a `_config_encoding`  field in `LuigiConfigParser` (in configuration.py).
I check the LUIGI_CONFIG_ENCODING environment variable to see if a value is given. 
If a value is given, I check in `codecs` whether the encoding exists or not and set the field to the encoding or None when the encoding is unknown (a warning message is sent).
If no value is given, I keep the field to None.

The documentation is updated accordingly in the configuration.rst file.
I took the liberty to change the level of configurable options [core], [worker], ... to simplify the navigation menu.

## Motivation and Context

I run Luigi on Windows. It opens configuration files with CP1252 encoding while they are in UTF8.

## Have you tested this? If so, how?
 

I created a small script in the example folder (hello_encoding_world.py) to test it.

### CODE REVIEW

**Comment by mpoussevin** [comment]
The first version was not considering Python2. 
Passing the `_config_encoding` to the `read()` method raised a TypeError.
I catch the error and fallback to default behaviour for Python2.

Is there a better way to do it ?

**Comment by Tarrasch** [comment]
Is the `-` to `*` conversion related to this?

**Comment by mpoussevin** [comment]
> Is the `-` to `*` conversion related to this?

Hello, I don't get which conversion you're talking about. Could you please tell me more ?

**Comment by dlstadther** [comment]
Also, please resolve merge conflict. Update with `master` branch

**Comment by dlstadther** [comment]
Hey @mpoussevin  I'm not sure we're communicating well related to the .rst changes. @Tarrasch and I have not been questioning the use of `*` or `-` as unordered list items, but rather the use of a sequence of them (`-------` or `*******`) for header denotation.

**Comment by mpoussevin** [comment]
Hello @dlstadther  

Thanks, I get it now. 
I propose using `---` for page title, `~~~` for level 1 sections (as in `doc/tasks.rst`) and `***` for level 2 sections (I couldn't find any .rst with level 2 sections though).

Tell me if that's OK !

**Comment by mpoussevin** [comment]
Wow. I don't get how changing only the `configuration.rst` file between commit 880a711 and 7aa39af breaks the `flake8` test.
Any idea ?

**Comment by mpoussevin** [comment]
OK, investigating further, I found out that setting UTF8 with the TOML parser yields `unicode` objects instead of  `str` objects : the `serialize` method from `Parameter` fails `str(u'hé')` fails in python 2. 
I don't want to change the behavior of `serialize`. I'll think of a way out.

**Comment by mpoussevin** [comment]
I don't think it's worth it, too many modifications in the core code to use Unicode for small benefits. 
Closing the PR.
Thanks guys.

**Pull request closed without merging**
