### PR TITLE
Add ConfigParser as the base class of LuigiTomlParser

### PR DESCRIPTION
**Pull request by fullflu**
## Description

This PR adds `ConfigParser` as the base class of `LuigiTomlParser` to use TOML configuration with S3 Client. Two files are changed:
- I modify `luigi/configuration/toml_parser.py`.
- I add `examples/foo_s3.py` to check the validity of my modification.

## Motivation and Context

It is pointed out that S3 Client doesn't work with TOML configuration #2698 .
Fixing the issue would help a lot of users because TOML configuration and S3 Client are useful.
Now I propose to fix the issue by a simple modification.

## Have you tested this? If so, how?
 

I do not add any unit tests.
Instead of unit tests, I add an example file (`examples/foo_s3.py`) to check the validity of my modification.
I confirm that my modification worked with S3 Client.
Please note that I have not confirmed that my modification does not cause other unknown errors.
I would be grateful that someone could review this PR.

## Details of tests

The details of the results of running `examples/foo_s3.py` are as follows.

Current LuigiTmolParser raises AttributeError (as described in #2698 ).

```
************:luigi *******$ LUIGI_CONFIG_PARSER=toml LUIGI_CONFIG_PATH=examples/config.toml PYTHONPATH=. python3 -m luigi --module examples.foo_s3 examples.Foo --local-scheduler
INFO     2019-08-16 23:36:38 setup_logging:86 logging configured via config section
WARNING  2019-08-16 23:36:38 worker:658 Will not run examples.Foo() or any dependencies due to error in complete() method:
Traceback (most recent call last):
  File "/Users/*******/projects/luigi/luigi/worker.py", line 409, in check_complete
    is_complete = task.complete()
  File "/Users/*******/projects/luigi/luigi/task.py", line 564, in complete
    outputs = flatten(self.output())
  File "/Users/*******/projects/luigi/examples/foo_s3.py", line 12, in output
    return S3Target("s3://ryft-public-sample-data/hoge")
  File "/Users/*******/projects/luigi/luigi/contrib/s3.py", line 673, in __init__
    self.fs = client or S3Client()
  File "/Users/*******/projects/luigi/luigi/contrib/s3.py", line 106, in __init__
    options = self._get_s3_config()
  File "/Users/*******/projects/luigi/luigi/contrib/s3.py", line 507, in _get_s3_config
    defaults = dict(configuration.get_config().defaults())
AttributeError: 'LuigiTomlParser' object has no attribute 'defaults'

INFO     2019-08-16 23:36:38 worker:595 Informed scheduler that task   examples.Foo__99914b932b   has status   UNKNOWN
INFO     2019-08-16 23:36:38 interface:172 Done scheduling tasks
INFO     2019-08-16 23:36:38 worker:1182 Running Worker with 1 processes
INFO     2019-08-16 23:36:38 worker:493 Worker Worker(salt=707699790, workers=1, host=************.local, username=*******, pid=2331) was stopped. Shutting down Keep-Alive thread
INFO     2019-08-16 23:36:38 interface:175 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed scheduling:
    - 1 examples.Foo()

Did not run any tasks
This progress looks :( because there were tasks whose scheduling failed

===== Luigi Execution Summary =====

```

Adding ConfigParser as the base class of LuigiTomlParser could solve the issue.

```
************:luigi *******$ LUIGI_CONFIG_PARSER=toml LUIGI_CONFIG_PATH=examples/config.toml PYTHONPATH=. python3 -m luigi --module examples.foo_s3 examples.Foo --local-scheduler
INFO     2019-08-16 23:36:51 setup_logging:86 logging configured via config section
INFO     2019-08-16 23:36:53 worker:595 Informed scheduler that task   examples.Foo__99914b932b   has status   PENDING
INFO     2019-08-16 23:36:53 interface:172 Done scheduling tasks
INFO     2019-08-16 23:36:53 worker:1182 Running Worker with 1 processes
INFO     2019-08-16 23:36:53 worker:165 [pid 2421] Worker Worker(salt=670023694, workers=1, host=************.local, username=*******, pid=2421) running   examples.Foo()
Running Foo that outputs S3Target
INFO     2019-08-16 23:36:53 worker:217 [pid 2421] Worker Worker(salt=670023694, workers=1, host=************.local, username=*******, pid=2421) done      examples.Foo()
INFO     2019-08-16 23:36:53 worker:595 Informed scheduler that task   examples.Foo__99914b932b   has status   DONE
INFO     2019-08-16 23:36:53 worker:493 Worker Worker(salt=670023694, workers=1, host=************.local, username=*******, pid=2421) was stopped. Shutting down Keep-Alive thread
INFO     2019-08-16 23:36:53 interface:175 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 examples.Foo()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====
```

### CODE REVIEW

**Comment by fullflu** [comment]
Hi @honnix @Tarrasch @dlstadther , I have checked that all existing tests passed.
Is there anything else to do?
I'd like to hear your opinion to fix the issue #2698 .

**Comment by dlstadther** [comment]
@fullflu I don't have experience with TOML. Your update is minimal, but i'm unaware of negative implications it could have.

Are you able to confirm that this change does not negatively impact any of your TOML configuration and luigi instantiation?

**Comment by fullflu** [comment]
@dlstadther 
I'm sorry that I cannot confirm the negative impact of this PR right now.

@orsinium 
Can you help me with the review of the negative impact of this PR...?

**Comment by orsinium** [comment]
@fullflu, thank you for taking care of it! I think it's a dangerous way to solve it. TOML and INI config parsers works in a totally different way, and all methods that are inherited in TOML parser from `ConfigParser` will give unpredictable results that are unrelated to the real values in the config.

> it seems like the interface of the two configuration objects should be standard.

This phrase from the issue is true. A good solution here is to add `class AbstractConfig(ABC):` that implements a common interface for both config parsers. And after that implement `.defaults()` method for the TOML parser as well with the expected behavior.

You can mention me for review if you want to take care of it. I value your current solution, it's short and beautiful but looks dangerous and unpredictable to me.

**Comment by fullflu** [comment]
@orsinium, thank you for your response! Now I understand the risk of this PR.

> A good solution here is to add class AbstractConfig(ABC): that implements a common interface for both config parsers.

How does the `LuigiTomlParser` use the AbstractConfig?  Does this use the inheritance as follows (`class LuigiTomlParser(BaseParser, AbstractConfig):`)?

> And after that implement .defaults() method for the TOML parser as well with the expected behavior.

I found that we need to implement not only `.defaults()` method but also `.items` method. It would not be so easy to cover all the methods used in various modules...
Therefore, I would to fix `s3.py` to handle TOML parser as a temporary solution.

**Comment by orsinium** [comment]
> Does this use the inheritance as follows (class LuigiTomlParser(BaseParser, AbstractConfig)

Yes, that looks good.

> I found that we need to implement not only .defaults() method but also .items method. It would not be so easy to cover all the methods used in various modules...

Let's start with something. You can implement ABC for current existing methods and `defaults` (and I recommend to keep it in separated issues). `items` can be implemented later.

**Pull request closed without merging**
