### PR TITLE
busybox compatibility for ps command usage in getpcmd, also use proc …

### PR DESCRIPTION
**Pull request by nmandery**
…filesystem first

This pull request makes the lock.getpcmp function compatible with the busybox implementation of the `ps` command. Also the function now attempts to use the `/proc` filesystem first.

## Description

The incompatibility to busybox `ps` came from the `ww` flags added to the command in PR #1809.

## Motivation and Context

This avoids error messages when using luigi for example on android devices.

## Have you tested this? If so, how?

Manually tested the function. Also ran the unittests, but these give me currently 8 errors on the master branch without any of my changes.

### CODE REVIEW

**Comment by Tarrasch** [comment]
I'm okay with luigi not working for everyone on every OS. Android feels like one such operating system. I'm suggesting you don't keep the backwards compatibility so the code can be simplified *a lot*

**Comment by nmandery** [comment]
I see, busybox compatibility may indeed stretch the scope of luigi a bit, although android devices are geting more and more powerful. Are you interested in the part of the pull-request using the /proc-filesystem when I just drop the part regarding the `ps` command?

**Comment by Tarrasch** [comment]
Yes. In fact I'm very interested. I'm sorry if my gratefulness didn't shine through in my previous comment. :)

However, this is what I suggest for now:

 * Close this PR.
 * Open a new one, but only keep the simplyfing `ps`-removing part. And as a comment in the code mentioning the limitation (busybox/android etc), and link to this PR.

Does that make sense?

**Comment by nmandery** [comment]
No worries ;)

I just checked [this article](https://www.kernel.org/doc/Documentation/filesystems/proc.txt) and indeed the `ps` command just reads the /proc filesystem:
 
> In  fact,  ps  uses  the  proc  file  system  to  obtain its information.

I guess there may be some setuid magic which allows `ps` to gather information from /proc without the user being able to read the filesystem directly.

Just to see if I understand you correctly: I am going to remove the parts using `ps` completely and add a few notes regading my experience on android.

**Comment by Tarrasch** [comment]
> Just to see if I understand you correctly: I am going to remove the parts using ps completely and add a few notes regading my experience on android.

Exactly, I would even link back to this PR. The purpose would be that you're first implementation isn't deleted, in case we some day in the future would like to actually support `ps` as fallback.

**Pull request closed without merging**
