### PR TITLE
Explicitly note that examples work with local_scheduler only.

### PR DESCRIPTION
**Pull request by themalkolm**
Update Interface.run as well to be able to specify local_scheduler
via kwargs.

Not sure but when I started learning luigi this documentation page
was super confusing as I constantly was getting some timeouts..

### CODE REVIEW

**Comment by Tarrasch** [comment]
This seems good. :)

**Comment by themalkolm** [comment]
ping

**Comment by erikbern** [comment]
I wonder if we should do something with `**kwargs` instead, but this looks good for now

**Comment by themalkolm** [comment]
Yep, if interface.run & interface.build share same kwargs than everything will be much easier.

**Comment by erikbern** [comment]
ok let's refactor interface.py soon. It's a bit messy. I've been thinking about ways to get rid of `EnvironmentParamsContainer` anyway so maybe let's try to do that first

**Pull request merged**
