### PR TITLE
Standardize the directory interface on FileSystem

### PR DESCRIPTION
**Pull request by mikekap**
This is the first step in bringing Google Cloud Storage support. While technically not necessary, I thought that it would be a nice refactoring.

 - is_dir vs isdir -> prefer the latter
 - list vs listdir -> prefer the latter
 - add listdir() to the base FileSystem interface, and implement it in a bunch of places

### CODE REVIEW

**Comment by erikbern** [comment]
LGTM

not sure why it fails on 2.7

**Comment by Tarrasch** [comment]
Cool! Awesome, while you're at it, here are some pointers for your endeavours:

 * See the rant I had in this old commit messsage and see it it's relevant: https://github.com/Tarrasch/luigi/commit/13085281c756b4f67935228d32765722fcaa4a58
 * For google cloud: See this [blogpost](http://alex.vanboxel.be/2015/04/13/luigi-and-google-cloud-in-production-retrospective/), and ask the owner if he wants to collaborate, he has some code [here](https://github.com/alexvanboxel/luigiext-gcloud) but he haven't pushed for a while it seems. :)

@alexvanboxel

**Comment by mikekap** [comment]
(Hopefully) fixed the test (missed a comma in contrib/target.py).

I looked at Alex's code, and I used it to get a feel for the GCS API, but it was rather incomplete. The implementation Vine uses is up to feature parity with S3 and comes with a test. My intent is hopefully to just upstream that implementation. I'm more or less just adding usage docs to it now, so once this goes in, expect another PR :)

**Comment by Tarrasch** [comment]
Cool! :D

**Comment by mikekap** [comment]
I think I have the GCS support ready @ https://github.com/spotify/luigi/compare/master...vine:gcs?expand=1 . If you could merge this, I'll rebase on top of master and send that PR.

**Comment by erikbern** [comment]
Nice!

**Comment by alexvanboxel** [comment]
Hi guys, I'll have a look and see if I can bring my other Google Cloud stuff (BigQuery and DataFlow support) back in line and remove my GCS support. One thing I'm missing while scanning diagonal over the pull request si a touch (like unix touch). It's a convenient way to write "_FLAG" files.

Otherwise if it's ok I'll implement a touch()

**Comment by Tarrasch** [comment]
Cool! I merged this so you can send your rebased change @mikekap.

The implementation doesn't need to be perfect to start with I suppose. I'll see if I can set up a gcs testing project and inject the right travis secrets so we also run the build matrix for the gcs. Let me know if there's any easy way for doing this. :)

**Pull request merged**
