### PR TITLE
moved installation instructions to the top

### PR DESCRIPTION
**Pull request by erikbern**
as well as links to documentation and examples

### CODE REVIEW

**Comment by erikbern** [comment]
side note is i noticed lots of links in the documentation are broken – i can fix today

**Comment by Tarrasch** [comment]
While you're at this, maybe also add instructions to running the tests? ie `tox -e pep8` and `tox -e py27-nonhdfs`

**Comment by erikbern** [comment]
Sure but let's not keep them at the top. I don't think it's very important for people to know how to run tests. But it should be documented somewhere yes.

**Comment by Tarrasch** [comment]
I meant like add it anywhere in the README. Feel free to merge this patch i meant. :)

**Pull request merged**
