### PR TITLE
Clarify file permission error message

### PR DESCRIPTION
**Pull request by xrmx**
Make it clear that permission should either be 'r' or 'w'.

The original "r/w" suggestion was not clear to me, was passing 'w+' originally, then interpreted the error as a request to use 'rw' until i looked at the actual source code :)

### CODE REVIEW

**Comment by bmaggard** [comment]
I like it, but while making the change, why not also them consistent?  I like the one I switched to back on PR #1456 (b/c: "(got: %s)"), but that can be reverted if others don't:

`raise Exception("mode must be 'r' or 'w' (got: %s)" % mode)`

**Comment by xrmx** [comment]
@bmaggard updated pull request to make them consistent.

**Comment by bmaggard** [comment]
This is good-to-go as far as I'm concerned.

**Comment by dlstadther** [comment]
No real critiques here. Improved error reporting 👍

**Comment by Tarrasch** [comment]
This looks very good, thanks!

One thing we should fix is that it shouldn't be such a general exception as `Exception()` right?

**Pull request merged**
