### PR TITLE
Forgive Failures

### PR DESCRIPTION
**Pull request by FxIII**
## Description
Let the user to forgive failures for failed tasks using the web interface.

## Motivation and Context
(issue #2035)
Failed tasks need to stay in their failed status for a while before being allowed to be run again if the workers are kept alive. Adding the forgive_failures feature to the scheduler, the user has the opportunity to acknowledge the error, perhaps fix it, and let the task to be run again.

## Have you tested this? If so, how?
I have extended the scheduler api unit test to check that forgive_failure allows a failed task to be retried and that is basically idempotent

### CODE REVIEW

**Comment by FxIII** [comment]
schermata 2017-04-16 alle 11 43 47

**Comment by Tarrasch** [comment]
Hehe, gotta love that cute ambulance icon. Anyway, the icon only appears on failed tasks, right? This looks goods to me. If nobody objects we can merge.

**Comment by Tarrasch** [comment]
@FxIII, I see you find errors, please also add test cases fixing stuff. In addition, maybe you want to run this version locally for 1 week and then we merge?

**Comment by FxIII** [comment]
@Tarrasch I simply removed an accidental paste fallen in a sector of code that is unrelated to my changes. I noticed that by inspecting the changeset (I try to keep it tiny for that reason). 
I didn't notice that in production, because it happen to be related to the d3 visualization (the way errors are shown) and we didn't use d3 visualization that much. 
The fact that such error didn't broke the regression test probably could fit the scope of another issue. Right now I can't figure out how to write down such a test (one should be able to simulate a click to a failed task in the d3 graph through phantomjs).

**Comment by Tarrasch** [comment]
@FxIII, okay. Thanks for looking into this. I'm ready to merge this. Is this PR ready to merge don your side too?

**Comment by FxIII** [comment]
@Tarrasch it is ok for me. Thanks

**Comment by mbelmadani** [comment]
How do I enable this feature? And is it only available in the github version of luigi or would the pip package also have it? Also would be nice to have some documentation on this too if this a configuration setting.

Looks like a great feature otherwise!

**Comment by Tarrasch** [comment]
It's auto-enabled but it's not released. Let's see if I can release it now.

**Comment by Tarrasch** [comment]
@mbelmadani it's now on pypi :)

**Comment by bmaggard** [comment]
My 2 cent suggestion (sorry it's late, I just stumbled on this feature): rename to "Retry" or "Reschedule".  To me, "Forgive failures" seems more like "mark Done"  (we are circumventing "retry_delay", after all).

**Comment by Tarrasch** [comment]
@bmaggard yes! That's a great idea to avoid introducing new terminology like "forgiving" since we already have "retry" meaning this. Can you send a PR with this small change?

**Pull request merged**
