### PR TITLE
Allows non-atomic ftp

### PR DESCRIPTION
**Pull request by daveFNbuck**
Part of my pipeline requires uploading files to an external server via ftp. The
server requires specific file names and rejects and deletes the temporary files
uploaded by RemoteTarget. In order to get around this, I've added an optional
atomic parameter to RemoteTarget.put. By running it with atomic=false, the
the target file is written to directly.

### CODE REVIEW

**Comment by Tarrasch** [comment]
LGTM. but is there any way to test this? :)

**Comment by daveFNbuck** [comment]
There are some tests in _test_ftp, but they won't actually run unless you set up an ftp server. We should probably add some more runnable tests that mock ftplib.

**Comment by Tarrasch** [comment]
Well, I assume they worked for you. I'm fine with merging given that you've tested this somehow. Have you?

**Comment by daveFNbuck** [comment]
Yeah, I'm currently using this code.

**Comment by Tarrasch** [comment]
Cool! Thanks again @daveFNbuck

**Pull request merged**
