### PR TITLE
Cleaning up global parameters & config parameters

### PR DESCRIPTION
**Pull request by erikbern**
Starting to deprecate global parameters and merging them with configuration options.

### CODE REVIEW

**Comment by Tarrasch** [comment]
I like the idea!

**Comment by erikbern** [comment]
It's an outcome of the long discussion in the luigi-user email thread. I'm working on a series of commits that will (a) remove global parameters (b) merge configuration and parameters.

These first few commits are the easy ones. There's some bigger ones coming. We can merge it as it is though.

**Comment by Tarrasch** [comment]
Yea, I'm totally fine with merging this. LGTM.

By the way, note that when I said 

> Would be nice to hear why you did this.

I commented on 6447179 in particular, not on this PR (#609).

**Comment by erikbern** [comment]
Will continue with the bigger stuff in a separate PR

**Pull request merged**
