### PR TITLE
don't call context managers directly, use the with statement

### PR DESCRIPTION
**Pull request by erikbern**
Follow up on #1431

### CODE REVIEW

**Comment by erikbern** [comment]
this one keeps failing on the visualizer test, but everything else works

**Comment by Tarrasch** [comment]
Could you look at disabling the intermittently failing visualizer tests? Maybe @stephenpascoe knows why?

**Comment by stephenpascoe** [comment]
The tests are failing because they expect 117 tasks to be in the scheduler but there are 162.  The simulated task tree should be deterministic.  I'll try it out locally.

**Comment by stephenpascoe** [comment]
When I grep the Travis logs for the visualiser tests I get 117 distinct tasks, as expected, but the scheduler says there are 162.  My guess is that the scheduler has tasks in it from a previous test.  I'd assumed it was isolated.

**Comment by Tarrasch** [comment]
I guess it's not completely isolated. Doh.

**Comment by erikbern** [comment]
did you change anything? not sure why it's building

anyway can i merge?

**Comment by Tarrasch** [comment]
I don't think I re-triggered it no. Or I might have done and forgot ^^

**Comment by Tarrasch** [comment]
Yes lets merge! :)

**Comment by erikbern** [comment]
maybe i re-triggered the build. anyway thanks!

**Pull request merged**
