### PR TITLE
Delete deprecated luigi/file.py

### PR DESCRIPTION
**Pull request by chalet16**

### CODE REVIEW

**Comment by kalvdans** [comment]
Better replace the internal uses of luigi.file with luigi.local_target first, a grep gives five hits.

**Comment by erikbern** [comment]
fine to merge assuming build failure is addressed

**Comment by dlstadther** [comment]
@chalet16 Could you address the references to `file.py` (mentioned by @kalvdans ) and fix the build errors? Thanks!

**Comment by Tarrasch** [comment]
ping @chalet16

**Pull request closed without merging**
