### PR TITLE
Fixed execution summary. Closes #1350

### LINKED ISSUE #1350: Argument parsing failing during execution summary
Execution summary couldn't generate arguments list.

```python
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 57, in main
    build([Crawler(user=dump(user, user.username))], workers=8)
  File "/usr/lib/python3.5/site-packages/luigi/interface.py", line 261, in build
    return _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)['success']
  File "/usr/lib/python3.5/site-packages/luigi/interface.py", line 195, in _schedule_and_run
    logger.info(execution_summary.summary(w))
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 384, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 333, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 132, in _get_str
    params = _get_set_of_params(tasks)
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 173, in _get_set_of_params
    params[param] = {getattr(task, param[0]) for task in tasks}
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 173, in <setcomp>
    params[param] = {getattr(task, param[0]) for task in tasks}
TypeError: unhashable type: 'dict'
```

params[param] must be params[param[0]]

### PR DESCRIPTION
**Pull request by aslafy-z**
dict index must be a string, not a tuple.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Add a test case perhaps?

**Comment by Xide** [comment]
This fix still traceback for me : 
```python
  File "/usr/lib/python3.5/site-packages/luigi/interface.py", line 261, in build
    return _schedule_and_run(tasks, worker_scheduler_factory, override_defaults=env_params)['success']
  File "/usr/lib/python3.5/site-packages/luigi/interface.py", line 195, in _schedule_and_run
    logger.info(execution_summary.summary(w))
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 385, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 334, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 132, in _get_str
    params = _get_set_of_params(tasks)
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 174, in _get_set_of_params
    params[param[0]] = {getattr(task, param[0]) for task in tasks}
  File "/usr/lib/python3.5/site-packages/luigi/execution_summary.py", line 174, in <setcomp>
    params[param[0]] = {getattr(task, param[0]) for task in tasks}
TypeError: unhashable type: 'dict'
```


This is corrected

 by replacing this line :
```python
params[param[0]] = {getattr(task, param[0]) for task in tasks}
```
with this one :
```python
params[param[0]] = [getattr(task, param[0]) for task in tasks]
```

in execution_summary.py:173

I still don't know why params was supposed to be filled with a dictionary, but it seems to work just well with a list instead.

**Comment by erikbern** [comment]
Great if you can make the tests pass

**Comment by Tarrasch** [comment]
Thanks for the PR! This should amend its commits, add a proper description of what it's actually fixing, include a test case and naturally pass the tests. :)

Good luck and again thanks for your contribution!

**Comment by erikbern** [comment]
will delete this PR unless it's amended

**Comment by Tarrasch** [comment]
Closing because of being inactive for a month. Please feel free to reopen whenever you have time to work on it. :)

**Comment by junchenfeng** [comment]
I got the bug in some of the task I ran, the task appears to be finished but it prevents dependent task from running.
`Traceback (most recent call last):
  File "users/update_mastery.py", line 153, in <module>
    luigi.run()
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 210, in run
    return _run(*args, **kwargs)['success']
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 238, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 198, in _schedule_and_run
    logger.info(execution_summary.summary(worker))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 384, in summary
    return _summary_wrap(_summary_format(_summary_dict(worker), worker))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 333, in _summary_format
    str_output += '{0}\n'.format(_get_str(group_tasks[status], status in _PENDING_SUB_STATUSES))
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 132, in _get_str
    params = _get_set_of_params(tasks)
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 173, in _get_set_of_params
    params[param] = {getattr(task, param[0]) for task in tasks}
  File "/usr/local/lib/python2.7/site-packages/luigi/execution_summary.py", line 173, in <setcomp>
    params[param] = {getattr(task, param[0]) for task in tasks}
TypeError: unhashable type: 'dict'`

**Pull request closed without merging**
