### PR TITLE
Moar tests.

### PR DESCRIPTION
**Pull request by themalkolm**
Make @Tarrasch happy.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Mur mur, I'm not happy about the commit message. :p

Hehe, thanks for the extra test cases. @themalkolm comment refers to #625

**Comment by themalkolm** [comment]
Well, what commit message would you like? This is my working message for adding more tests in my projects :)

**Comment by erikbern** [comment]
Let's just merge. We don't have to be perfect about everything, especially with tests

**Comment by Tarrasch** [comment]
Haha, yea yea, I'm totally fine with merging this :) (It would be good if the commit message did actually mention "#625". For next time.)

**Pull request merged**
