### PR TITLE
Keep track of num failed tasks for a worker.

### PR DESCRIPTION
**Pull request by dhruvg**
Add bookkeeping for number of failed tasks when getting work from the scheduler and workers.

### CODE REVIEW

**Comment by dhruvg** [comment]
@erikbern Any idea what is up with the builds? Doesn't seem to be a code issue.

**Comment by dhruvg** [comment]
@erikbern My hunch is that it is impacting the performance of that test case since it is called `get_work` thousands of times and we are now calculating num failed tasks on each request.

**Comment by dhruvg** [comment]
@erikbern bump?

**Comment by erikbern** [comment]
anyway this was closed? i guess it's been sitting here for a long time, not sure why

**Comment by Tarrasch** [comment]
After a quick glance of the code I don't understand it. It just threads along the variable but it never seems to print or use it for anything. Anyway still looks interesting. :)

**Pull request closed without merging**
