### PR TITLE
Fixes for some issues with task history

### PR DESCRIPTION
**Pull request by erikbern**
See https://github.com/spotify/luigi/commit/7707525a4f929226acfb0cd10e5667ddee8ec9cd

@jbalogh do you think this resolves the issue?

### CODE REVIEW

**Comment by jbalogh** [comment]
It certainly looks like it. Do you think there was anything relying on the default `scheduler` argument always being the same object?

**Comment by erikbern** [comment]
No, the `Worker` object shouldn't be instantiated anywhere else than from interface.py, so it should be fine

**Comment by jbalogh** [comment]
Thanks for fixing this so fast!

**Comment by erikbern** [comment]
Cool can you let me know if the problem persists?

**Comment by jbalogh** [comment]
I pulled the latest and I'm not seeing any issues.

**Comment by erikbern** [comment]
Great – I'll make another release tomorrow morning, hopefully the last one for a while (there was a rapid succession of bugfixes)

**Pull request merged**
