### PR TITLE
Scheduler keeps resources for each worker

### PR DESCRIPTION
**Pull request by TKNGUE**
Scheduler keeps resources for each worker

## Description
  Change the scheduler's behavior so that it keeps the resources for
  each worker.
  The change provide dynamically scheduling of resources.

## Motivation and Context
  Conventional implementation cannot support Dynamic resource allocation.
  Users strongly wish the feature.

## Have you tested this? If so, how?
I ran my jobs with this code and it works for me.

### CODE REVIEW

**Comment by daveFNbuck** [comment]
Is there a reason you're doing this per-worker rather than per-host like in #1669?

**Comment by TKNGUE** [comment]
Firstly, I tried to do so. But, It has a problem.
When new workers have launched, resource information that scheduler keeps is overwritten
due to synchronizing to task states of workers by the implementation of luigi.
I thinks it is undesirable. That means that the behaviors of running tasks can be changed by launching the new worker. 
So I keep the resource information by worker id instead of host.

**Comment by daveFNbuck** [comment]
Ah, so this is actually making tasks have different resources depending on the worker, rather than having worker-based limits? This is completely different from the features desired in #1872 and #1362. Perhaps you can better explain what the purpose of this is? Why would resources used change depending on who's running it?

**Comment by TKNGUE** [comment]
I'm sorry for my misunderstanding about the issues.

The PR have the mainly two purpose
Let me taking a example.

When If I implemented following, this is a dynamic resource allocating example.
```python
class TaskA(luigi.Task):
    param = luigi.Parameter(1)

    @property
    def resources(self):
          import os
          return os.uname().nodename
# ...  Define requires and run

     def run(self):
     # ... heavy process

luigi.build([TaskA(1), TaskA(2)])
```
In this example, needed resources of the task are decided at launched.
If you run the program by workers in different host, namely _host1_ and _host2_ , 
the scheduler get workers to run as my expectation, but it doesn't.

According to my analyze, this is due to override the resource information scheduler keep by newly launched worker ( This is ``add_task``'s behavior ).
My PR protected from the overwriting. (Keeping host-based limitation will cause same problem)

I thinks the PR enable task to allocate resources more dynamically.

**Comment by daveFNbuck** [comment]
I think your example fits the use case of #1669 pretty well.

**Comment by TKNGUE** [comment]
Okay. thanks.  I close this issue.

**Pull request closed without merging**
