### PR TITLE
Drop python 2.6 support.

### PR DESCRIPTION
**Pull request by themalkolm**
Remove leftovers.  Note sure what it is but this is clearly for 2.6 :D

### CODE REVIEW

**Comment by Tarrasch** [comment]
Looks good to me!

**Comment by gpoulin** [comment]
Indeed, that was needed for retrocompatibility, to be able to write both unicode and str to file in python2.6

**Comment by Tarrasch** [comment]
Mind fixing the build failure @themalkolm ?

**Comment by themalkolm** [comment]
Waiting for this one to be merged first https://github.com/spotify/luigi/pull/989 :D

**Comment by Tarrasch** [comment]
@themalkolm Done (was it even related??)

**Comment by themalkolm** [comment]
@Tarrasch nope, but I prefer to do it this way :dancer:

**Comment by Tarrasch** [comment]
Care to resubmit this @themalkolm? :)

**Comment by themalkolm** [comment]
My kung-fu is too weak to solve it. I don't really see why this code should be deleted for python 2.7 actually.

**Comment by Tarrasch** [comment]
Can you look at the error @gpoulin?

**Comment by Tarrasch** [comment]
@gpoulin, you understand this code the best I think. Any insights to share? Would be nice to see this patch fixed and merged. :)

**Comment by gpoulin** [comment]
@Tarrasch Sorry I was quite busy with moving and starting of a new job recently. However, I will find some time by the beginning of next week.

**Comment by Tarrasch** [comment]
Congrats on the new job @gpoulin, wherever it is! :)

Oh, will you be able to use Luigi in your new job? ^^

**Comment by Tarrasch** [comment]
Closing in favor of #1065

**Pull request closed without merging**
