### PR TITLE
Reduce TravisCI Test Runtime

### PR DESCRIPTION
**Pull request by dlstadther**
Travis tests are taking way too long (and we're being too greedy with their free resources). Trying to reduce the overhead here.

## Description

Brute force nose attributes of (`apache`, `aws`, `contrib`) excluded from `core` (previously `nonhdfs`). (`apache`, `aws`) will be added for most recent Python 2.X and 3.X versions.

## Motivation and Context

CI needs to be quicker - seeing what can be done to segment differently.

## Have you tested this? If so, how?
 

TravisCI :)

### CODE REVIEW

**Comment by dlstadther** [comment]
py-27-aws only adds 2:30m

**Comment by dlstadther** [comment]
Not immediately sure why apache tests ran some postgres stuff. Will look into this more at a later time.

**Comment by dlstadther** [comment]
py27-apache <2m

**Comment by dlstadther** [comment]
< 10m build

**Comment by dlstadther** [comment]
@Tarrasch @honnix @ulzha 
Looking to get one more :+1: before merging.

The only contribution negative is that new TestCases in `/tests/contrib/` will need to add a Nose Attr label, otherwise will be included in `core`

**Comment by honnix** [comment]
Looks awesome. Good job!

Just one minor comment. `apache` refers to `Apache Hadoop Ecosystem`, right? Wonder whether this name would be too generic. On the other hand, I think people will get it.

**Comment by dlstadther** [comment]
Correct. `apache` -> apache hadoop ecosystem

Thanks for taking a look!

**Comment by Tarrasch** [comment]
Awesome! :dancer: :tada:  :balloon: :100:  :trophy:

**Pull request merged**
