### PR TITLE
Add RDBMS Query abstract class, PostgresQuery and RedshiftQuery subclasses (revived)

### PR DESCRIPTION
**Pull request by alexdebrie**
This is reviving #1289 and fixing the broken tests.

### CODE REVIEW

**Comment by Tarrasch** [comment]
LGTM. @moandcompany maybe wants to review? It's always fun to see patches getting revived by another user (showing that more than one person cares about it). :)

**Comment by dlstadther** [comment]
LGTM.

**Comment by Tarrasch** [comment]
Thanks @alexdebrie !! :)

**Comment by alexdebrie** [comment]
Thanks to you and the rest of the maintainers for all your work!

**Pull request merged**
