### PR TITLE
Adds tests for run_and_track_hadoop_job

### PR DESCRIPTION
**Pull request by daveFNbuck**
As requested in #1299. This tests extraction of information from stderr
and raising an error on non-zero exit codes.

### CODE REVIEW

**Comment by erikbern** [comment]
wow this is fantastic! Thanks so much!

**Comment by daveFNbuck** [comment]
ping

**Comment by Tarrasch** [comment]
I wanted to wait to merge to not cause bugs in 2.0.0 release. But this seems well tested (and I assume you've tested it in production too)

**Comment by daveFNbuck** [comment]
Ah, I forgot that I had added the second commit that wasn't just tests.

**Pull request merged**
