### PR TITLE
breaking: Remove deprecated contrib redirections

### PR DESCRIPTION
**Pull request by Tarrasch**
## Description

After this commit the following imports will no longer work

    import luigi.s3
    import luigi.postgres

Instead use

    import luigi.contrib.{s3,postgres}

This is a continution on spotify/luigi#1997

## Motivation and Context

This will make it clear that these modules should not be considered core luigi. 

## Have you tested this? If so, how?

I ran some tox-tests locally. But I mainly rely on Travis here.

### CODE REVIEW

**Comment by Tarrasch** [comment]
>  I think the merge of this PR should result in release 2.7. Thoughts?

Sounds good to me. I guess people will be more careful upgrading to a minor bump. Plus we've had many other nice contributions since last release. :)

**Comment by dlstadther** [comment]
@Tarrasch Thoughts on when to merge this? (and release a new version)

**Comment by dlstadther** [comment]
@Tarrasch Following up here regarding merging this PR (and maybe a few other small ones) and releasing the next large Luigi Version. Thoughts?

**Comment by Tarrasch** [comment]
@dlstadther totally agree, I've just been a bit lazy. Sorry about that. :)

**Pull request merged**
