### PR TITLE
Silence false positive UnconsumedParameterWarning

### PR DESCRIPTION
**Pull request by starhel**
UnconsumedParameterWarning is emitted even if parameters are correctly consumed. 

## Description
There are two cases when UnconsumedParameterWarning is false positive:
* camelCase or parameters with dashes in name are not correctly recognized when cfg parser is used.
* Some parameters are defined in core section of config (autoload_range, no_configure_log), but are not needed in class instance (as must be used before class is initialized).

## Motivation and Context
False positive UnconsumedParameterWarning forced me to completely disable this feature as any output to stderr is treated as error in pipelines. 

## Have you tested this? If so, how?
I've added unitests and tested this branch in my pipeline.

### CODE REVIEW

**Review by andresgomezfrr — APPROVED** [review]
LGTM

**Comment by starhel** [comment]
@andresgomezfrr Do you have any idea how to fix codecov?

**Review by dlstadther — APPROVED** [review]

**Comment by andresgomezfrr** [comment]
> @andresgomezfrr Do you have any idea how to fix codecov?

Could you try to update this branch with master?

**Comment by starhel** [comment]
Branch was updated, I've forced CI to retest PR.

**Review by dlstadther — APPROVED** [review]

**Comment by dlstadther** [comment]
Apologies for not merging this sooner!

**Comment by tashrifbillah** [comment]
I am using Luigi 3.5.2, the latest. But I still have these warnings!

**Pull request merged**
