### PR TITLE
Corrected PR #996 according to comments in #995.

### PR DESCRIPTION
**Pull request by kianho**
- Changed S3CopyToTable.s3_load_path back to a method according to the
  suggestion: https://github.com/spotify/luigi/issues/995#issuecomment-123896142

- Modified the accompanying test case accordingly.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Please review @carlineng

**Comment by carlineng** [comment]
Looks good, thank you @kianho

**Comment by Tarrasch** [comment]
And there's no issues with breaking backward compatibility here guys? Or it just unbreaks what it previously broke?

**Comment by carlineng** [comment]
Correct, this simply reverts the change made in spotify/luigi#996, which broke the redshift S3CopyToTable task.

**Comment by kianho** [comment]
@Tarrasch, correct, it unbreaks #996

**Comment by joeshaw** [comment]
`s3_load_path` is still decorated as `@abc.abstractproperty` -- should it be changed to `@abc.abstractmethod`?  I was using it as a property so this commit broke some of my code (was previously using 1.3.0 and upgraded to master.)

**Comment by spiside** [comment]
@joeshaw I noticed that too re: `@abc.abstractproperty`. I'm thinking of making a couple more changes to the redshift module and will be addressing that point.

**Comment by dlstadther** [comment]
It appears that @kianho 's PR intended to change `s3_load_path` back to a method (as noted by the used of `self.s3_load_path()`). However, [L72](https://github.com/spotify/luigi/commit/9136cd0424a62154799badd21a8b75a64d9689af#diff-778ea3db4cccaf4de6564889c5eb670fL72) shows that the decorator change never occurred.

No one (including myself) had picked up on the inconsistent use of an `@abc.abstractproperty` being called as a method (`self.s3_load_path()`).

I will update this in my existing pending PR #1393

**Comment by kianho** [comment]
good spot @dlstadther, apologies for the oversight.

**Pull request merged**
