### PR TITLE
raise an error when no columns are found

### PR DESCRIPTION
**Pull request by maxcountryman**

### CODE REVIEW

**Comment by dlstadther** [comment]
By default `rdbms.py` sets `columns = []` so your conditional addition should catch when the user does not override this variable.

lgtm

**Comment by dlstadther** [comment]
@Tarrasch Any reason not to merge this?

**Comment by Tarrasch** [comment]
Isn't all the tests failing due to indentation error?

**Comment by dlstadther** [comment]
Ah, yes. The `else` block appears to line up with the method declaration. @maxcountryman , you'll need to indent your additions to line up with rest of the conditional.

**Comment by Tarrasch** [comment]
That also raises the question of how much this was tested (if at all). 

@maxcountryman, can you also add a motivation to this patch? What real world use case scenario does it solve for you?

**Comment by maxcountryman** [comment]
@Tarrasch did you read the commit message...?

**Comment by Tarrasch** [comment]
@maxcountryman I did not, sorry! Thanks, it explains it well. I'm too used to GitHub copying it into the PR description. :)

**Comment by dlstadther** [comment]
Ready to merge?

**Pull request merged**
