### PR TITLE
tox: Remove all code coverage tools

### PR DESCRIPTION
**Pull request by Tarrasch**
## Description
Remove all code coverage tools.

## Motivation and Context
I removed "coverage" and "codecov" (I don't even know their difference).
At the moment I want to minimize the cruft. Also the output is smaller
and less verbose when our first-time-users test their code with tox.

I wasn't sure what "sitecustomize.py" is, but the less magic the better
for now. Given that nobody currently have strong ownership over luigi,
it's better to strip the project to a manageable size.

### CODE REVIEW

**Comment by erikbern** [comment]
coverage seems useful to track though

**Comment by Tarrasch** [comment]
Does anybody have trust in that tool (in luigi's setting). I think that it's something added a long time ago and currently nobody on board luigi knows how it works and what number it actually is reporting.

Let's remove it. Since we use version control adding it back is trivial once somebody takes the initiative to do so.

**Comment by erikbern** [comment]
i have trust in it. i added it a while ago and have been using it to track coverage.

it's something that adds credibility to luigi (i hope) by demonstrating that test coverage is reasonable

**Comment by erikbern** [comment]
no idea what sitecustomize does though – can prob remove that

**Comment by gpoulin** [comment]
The `sitecustomize` is there to fix wrong reporting with multiprocessing. Luigi does some of its tests in a subprocess (server, MapReduce, ...). The issue is that the coverage context is not transfer automatically to the child process, meaning that any coverage done in a child process won't be reported. So removing this `sitecustomize` will wrongly reduce the coverage reported. However, it seems to be fixed in coverage 4.0 with the option `--concurrency=multiprocessing`.

Also if you decide to remove the coverage, go ahead and remove `.coveragerc` at the same time ;)

**Comment by Tarrasch** [comment]
> it's something that adds credibility to luigi (i hope) by demonstrating that test coverage is reasonable

Yea. This is true, and actually maybe one of the biggest reasons that new companies still prefer luigi over the rightfully tempting airflow alternative. :)

Thanks for your comment @gpoulin.

I'm closing this. I'll look into

 1) Create one PR only removing codecov.io
 2) One PR removing sitecustomize and replacing it with the `--concurrency=multiprocessing` flag @gpoulin just informed me about. :)

**Comment by stevepeak** [comment]
@Tarrasch I'm from the Codecov team. If you would like more information on what we can help with please let me know. It seems that your team values coverage, but I'm unsure why you are removing Codecov from Luigi? Thank you

**Comment by Tarrasch** [comment]
Thanks for joining in @stevepeak. I wanted to remove codecov because of it often posts annoying unuseful comments to PR's.

https://github.com/spotify/luigi/pull/1670#issuecomment-215302020
https://github.com/spotify/luigi/pull/1669#issuecomment-215587677
https://github.com/spotify/luigi/pull/1675#issuecomment-216375738

I suspect the numbers are not correct. I'm sure this can be fixed. But I didn't have the time and nobody else have stepped up so far.

I think what Erik said was the the number reported by coverage is useful (the shiny badge on the readme). @stevepeak, is it a good/normal thing for python projects to utilize both "coverage" and codecov.io? Are they solving different or the same problem? I would be happy to only use one to minimize maintenance

**Comment by Tarrasch** [comment]
I'm closing this to clarify that this is not meant to be merged anymore. I think I just forgot to do it from https://github.com/spotify/luigi/pull/1693#issuecomment-220876452.

**Comment by erikbern** [comment]
we can turn off the PR comments, i also find them pretty useless

**Comment by Tarrasch** [comment]
@stevepeak, we keep getting these annoying notifications from the codecov bot. Is there any way to make it stop? For example https://github.com/

**Comment by stevepeak** [comment]
Sure, you can turn them off for the entire organization or a simple project in you configuration file:

`codecov.yml` in your repository. Or at https://codecov.io/account/gh/spotify/yaml
```
comment: false
```

**Comment by Tarrasch** [comment]
Ah. This seems to be the link describing how to configure [codecov.yml](https://github.com/codecov/support/wiki/codecov.yml#). It should be noted that there's not web ui to configure codecov (which I think is very good :))

**Pull request closed without merging**
