### PR TITLE
Accept date_interval classes as arguments for relevant parameter types.

### PR DESCRIPTION
**Pull request by lallea**
## Description

Allow date_interval.{Month,Year} to be used as arguments for {Month,Year}Parameter.

## Motivation and Context

The date_interval classes are useful for date arithmetic. Allowing them to be used to fill parameter values saves a confusing '.date_a' when using them for calculating values in requires().

## Have you tested this? If so, how?

Added unit tests. Ran tests locally. No additional test failures.

### CODE REVIEW

**Comment by Tarrasch** [comment]
> Allowing them to be used to fill parameter values saves a confusing '.date_a' when using them for calculating values in requires().

Shouldn't one aim for "easy to read" code rather than "easy to write"? Won't a reader be a bit confused that it is possible to pass a pair of dates to something that expects a single date?

----

Also let's add docs if we decide to merge this.

**Comment by lallea** [comment]
I agree, easy to read >> easy to write. See difference in example at end of comment. I find that the ".date_a" adds confusion for the reader. 

Parameters typically do not denote a point in time, but an interval, e.g. events collected during one day, active users during one month, etc. Looking again, however, I see that there is a DateIntervalParameter, and that the proposed change does not make sense for DateParameter.

I think that it does for MonthParameter and YearParameter, however. They match date_interval in the sense that they specify a specific, aligned date range.

I'll remove the change to DateParameter and add docs.


Before PR:

class MyRecursiveTask(Task):
  month = MonthParameter(default=Month.from_date(date.today()).prev().date_a)

  def requires(self):
    return {'previous_month": MyRecursive(Month.from_date(self.month).prev().date_a)}

After PR:

class MyRecursiveTask(Task):
  month = MonthParameter(default=Month.from_date(date.today()).prev())

  def requires(self):
    return {'previous_month": MyRecursive(Month.from_date(self.month).prev())}

**Comment by lallea** [comment]
I corrected the docs a tiny bit.

**Comment by dlstadther** [comment]
Could you merge master (for moto test success)?

**Comment by lallea** [comment]
Merged master.

**Pull request merged**
