### PR TITLE
Fix for #995.

### PR DESCRIPTION
**Pull request by kianho**
Simple correction to redshift.py.
See #995 for details.
@rantav @ddaniels888

### CODE REVIEW

**Comment by Tarrasch** [comment]
A test case would be nice too of course. :)

**Comment by kianho** [comment]
good idea, will address it over the next few days or so.

**Comment by Tarrasch** [comment]
Yea, given how "trivial" mistake you've found, it seems like this module have been a bit under tested.

**Comment by kianho** [comment]
Since this will be testing S3CopyToTable, which involves both s3 and redshift connectivity, should my test(s) be placed in `test/redshift_test.py` or `test/s3_test.py`?

**Comment by Tarrasch** [comment]
I have no strong opinion. But I would say `test/contrib/retshift_test.py` (move it into `test/contrib/ as well, while you're at it), because the code seem to be defined there.

**Comment by kianho** [comment]
The CI for this PR seems to be failing only on `py33-nonhdfs`, however it is due to a (seemingly) unrelated unit test: https://travis-ci.org/spotify/luigi/jobs/65873895#L1430
any thoughts on how to proceed?

**Comment by Tarrasch** [comment]
Cool! Thanks for the patch! :)

**Comment by kianho** [comment]
No worries, happy to help :)

**Pull request merged**
