### PR TITLE
Update tornado version

### PR DESCRIPTION
**Pull request by dlstadther**
## Description

Check for compatibility of tornado's new milestone release

## Motivation and Context

Tornado 5.1.0 has been released. Also, a [community member asked if Tornado >=5 was compatible](https://groups.google.com/forum/#!topic/luigi-user/ABJ3SKnkNHU)

## Have you tested this? If so, how?
 

Travis :)

### CODE REVIEW

**Comment by dlstadther** [comment]
@Tarrasch  You good with this for validation of compatibility?

**Comment by Tarrasch** [comment]
> @Tarrasch You good with this for validation of compatibility?

Yep, I can't think of anything else that's needed.

**Comment by honnix** [comment]
It is probably worth noting that Python 2.7.9+ or 3.4+ is required by Tornado.

```ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).```

**Comment by honnix** [comment]
Of course a force downgrade would solve it but looks quite bad.

**Comment by honnix** [comment]
wdyt @ulzha @Tarrasch ?

**Comment by ulzha** [comment]
+1

**Pull request merged**
