### PR TITLE
Squashed sqlabugs branch

### LINKED ISSUE #643: Update SQLA module
@erikbern @Tarrasch 
I have been testing the sqla module to incorporate sqlalchemy based task. I have identified some improvements that bring enhancements and fixes, namely:

- Insertions in marker table is NULL in MySQL
- Enhance sqla.CopyToTable to allow table updates apart from insertions

This is a placeholder to bring in these improvements.

### PR DESCRIPTION
**Pull request by gouthambs**
Fixes #643.
Lot of good discussions in #644

### CODE REVIEW

**Comment by gouthambs** [comment]
@erikbern all the `sqla` docs are missing again!

**Comment by erikbern** [comment]
that's weird, do you know why?

**Comment by gouthambs** [comment]
don't have a clue. I will look. I remember you fixed something last time. Wonder if something broke in between.

**Comment by gouthambs** [comment]
@Tarrasch @erikbern I can't figure out why the docs don't get generated for sqla module. This is really weird. Can some else one take a look at this?

**Comment by Tarrasch** [comment]
Not sure I can help here.

**Pull request merged**
