### PR TITLE
display parameters in /history

### PR DESCRIPTION
**Pull request by glenndmello**
The /history view would be a bit more useful with the parameters that the task used.

### CODE REVIEW

**Comment by Tarrasch** [comment]
@jcrobak, you know about the history server the most. Do you want to review? :)

**Comment by Tarrasch** [comment]
Can you rebase on master and force push again?

**Comment by jkukul** [comment]
@glenndmello, I'd also find this useful. Any chances for the rebase and push?

**Comment by Tarrasch** [comment]
Want to rebase @glenndmello? Alternatively you can too @jkukul :)

**Comment by glenndmello** [comment]
I've merged spotify/luigi. 
Cheers.

**Comment by erikbern** [comment]
You should have rebased on master not merged with master. But anyway seems like this commit is small enough that GitHub figured out what the diff was. We can merge this.

**Comment by Tarrasch** [comment]
See #1050

**Pull request closed without merging**
