### PR TITLE
Added a note about the problem in issue #1726.

### PR DESCRIPTION
**Pull request by dmyersturnbull**

### CODE REVIEW

**Comment by Tarrasch** [comment]
LGTM

**Comment by daveFNbuck** [comment]
I'm not familiar with this issue, and I still don't understand it after reading and re-reading the new documentation several times. Could you please be more clear about what will happen if you do
```
[Outer]
x=eleven
```
versus
```
[Inner]
x=eleven
```
and create instances of both Outer and Inner?

**Comment by dmyersturnbull** [comment]
@Tarrasch Do you have an idea how to make this clearer?

**Comment by erikbern** [comment]
would prefer if you put this in the documentation for `@requires` instead. configuration is a lot more common and i don't want to add unnecessary complexity to the documentation there

**Comment by Tarrasch** [comment]
@dmyersturnbull,

Here's what I think you could do to make it clearer:

 * Move the docs as @erikbern said
 * In the docs for configuration. Perhaps only add a sentence saying something like "Any configuration done to a luigi task will never affect anything but instances of that class,  not superclasses nor subclasses.". Luigi never cares in what way a task parameter came to be (weather it's through inheritance, `@requires` or explicit retyping). Parameter objects are also immutable and more functional than object oriented.
 * Come up with a more creative name than Inner/Outer.

**Comment by Tarrasch** [comment]
@dmyersturnbull, there's a flake8 issue. Can you resolve that?

**Comment by dmyersturnbull** [comment]
@Tarrasch It looks fine to me. Do you see where the issue is?

**Comment by Tarrasch** [comment]
Not sure. I would look for other existing examples in the docs and see how your code differs. As noted in CONTRIBUTING.md, you can debug this locally too using `tox`

**Pull request closed without merging**
