### PR TITLE
Presto support in Luigi

### PR DESCRIPTION
**Pull request by drowoseque**
## Description
I've added presto support in luigig

## Motivation and Context
Presto is a distributed sql engine that supports different DBs such as Hive, Postrgres, Cassandra etc
https://prestodb.io/

## Have you tested this? If so, how?
I have included unit tests.
I ran my jobs with this code and it works for me.

### CODE REVIEW

**Comment by drowoseque** [comment]
@honnix 
@dlstadther 
@Tarrasch 
PTAL

**Comment by honnix** [comment]
@drowoseque Sorry for replying late. I cannot give more constructive comments than "please add docstring to publish method/properties". Is there anyone from your side who can take a look?

**Comment by drowoseque** [comment]
maybe @b2arn can take a look

**Comment by drowoseque** [comment]
@honnix 
can't figure out why codecov thinks I have unexpected cov changes

**Comment by drowoseque** [comment]
@honnix @dlstadther @Tarrasch 
all checks turned into green
can we go on with merge?

**Comment by Tarrasch** [comment]
I honestly didn't look at the code. But I'm happy you've fixed the initial feedback and @b2arn looked at this.

**Pull request merged**
