### PR TITLE
Unpack parameter tuples on MixinNaiveBulkComplete

### PR DESCRIPTION
**Pull request by thejens**
Change-Id: I8ce61b8736de87c77a5d3250f72a803bfd5aaf49

### CODE REVIEW

**Comment by thejens** [comment]
"parameter_tuples" was not handling an iterable of tuples. 

Updated to work on iterable of tuples or lists as well as iterable of dict

Intension is to keep original behavior if "parameter_tuples" contains single parameters instead of tuples

**Comment by erikbern** [comment]
lgtm but can you add a test?

**Comment by thejens** [comment]
will do

**Comment by thejens** [comment]
Added tests

**Comment by erikbern** [comment]
excellent

**Comment by thejens** [comment]
reopened as https://github.com/spotify/luigi/pull/1508 due to accidental merge and then fail to reset branch :(

**Pull request closed without merging**
