### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by aadu**
Fixed the relative path of the sphinx include directive so that it can find README.rst.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Seems like the doc build failed because of this ...

**Comment by berkerpeksag** [comment]
The patch LGTM in my opinion. Currently, the index page at http://luigi.readthedocs.org/en/latest/ is broken (relevant commit is https://github.com/spotify/luigi/commit/7d0b4ec1215059d340cd9711a584abaca44fd49c)

`tox -e docs` command can be simplified. Sphinx already provides some useful make rules. `make -C doc linkcheck` for example. I'll open a PR to simplify it.

**Comment by Tarrasch** [comment]
Thanks @berkerpeksag, you're like an guardian angel for our continuous integration! :)

**Comment by erikbern** [comment]
Currently some build issue but I think it's because this has to be rebased. I'll fix it if it causes build issues in master

**Pull request merged**
