### PR TITLE
Fix examples: foo_complex.py luigi run arguments to include task namespace

### PR DESCRIPTION
**Pull request by moandcompany**
Fixes run arguments in `foo_complex.py` example

### CODE REVIEW

**Comment by Tarrasch** [comment]
Really awesome! Can you just fix the flake8 error?

**Comment by moandcompany** [comment]
@Tarrasch Yeah, no problem -- I'll take a look tonight. I'd also like to add some an example for monitoring S3 objects

**Comment by Tarrasch** [comment]
Go for it :)

**Comment by moandcompany** [comment]
Cool - figured out the flake8 error was coming from the fact the Travis is configured to test using Python 3

**Comment by Tarrasch** [comment]
Thanks! I've for a long time missed a simple hello world example :)

**Pull request merged**
