### PR TITLE
Tests for S3 put kwargs (SSE)

### PR DESCRIPTION
**Pull request by jpiper**
These tests check that server-side-encryption (SSE) works with the my `**kwargs` patch.

Whilst this isn't the best set of tests (I don't test any of the other flags), some tests are better than no tests :) Work with moto - unfortunately don't have the permissions here to test on S3 proper.

### CODE REVIEW

**Comment by erikbern** [comment]
great!

**Comment by jpiper** [comment]
Oops - code style tests now pass.

**Comment by Tarrasch** [comment]
Amend commits please :)

**Comment by jpiper** [comment]
I think this is what you're asking for? My git skills are severely lacking...

**Comment by Tarrasch** [comment]
Exactly. Thanks for quick reponse!

+1

**Pull request merged**
