### PR TITLE
fix for 'allow binary opens'

### PR DESCRIPTION
**Pull request by bmaggard**
The previous commit's intent was to enable 'binary' mode. This commit fixes it, preventing 'append' and 'update' modes.

### CODE REVIEW

**Comment by erikbern** [comment]
lgtm

**Comment by erikbern** [comment]
would prefer tests but not blocking

**Comment by bmaggard** [comment]
I'll see what I can do re:tests, sorry.

**Comment by Tarrasch** [comment]
Yea. Tests would be very nice. :)

Bonus points if you also put the problem description in the commit message (not necessary)

**Comment by Tarrasch** [comment]
Are you still iterating on this @bmaggard ? Can the commits be squashed?

**Comment by bmaggard** [comment]
Sorry for the delay.  I will get the commits squashed.

**Comment by bmaggard** [comment]
Squashed back into PR #1452.  Please let me know if that was wrong.

**Comment by Tarrasch** [comment]
There are merge conflicts so I cannot merge. Make sure to have rebased your change on the latest HEAD.

**Comment by erikbern** [comment]
next time please squash the small commits :)

**Comment by bmaggard** [comment]
Sorry about that; I was planning to, but I was still scratching my head on the Jarvis failure and kept getting distracted.  It didn't seem to be related to anything I did, but I wasn't sure.  

I plan to level-up on my git skills soon.

**Pull request merged**
