### PR TITLE
test if travis fail with process instead of thread

### PR DESCRIPTION
**Pull request by gpoulin**
On my local machine starting the server in a process instead of a thread seems to make the tests fail as expected.

### CODE REVIEW

**Comment by gpoulin** [comment]
Don't merge this, it's really draft. If it works I'll create a PR with only modification in `server_test.py`.

**Comment by gpoulin** [comment]
It seems to work I'll do one more test.

**Comment by gpoulin** [comment]
I kept the two commits to keep reference of the two Travis build. When everything seems OK and if you want to merge let me know I'll squash the commit and give a better description.

@Tarrasch this should fix #759.

**Comment by gpoulin** [comment]
https://travis-ci.org/spotify/luigi/jobs/51936789#L388 ??? That shouldn't have passed and it fail on my local machine. Anyway I would say merge and try to see why it passes later. I'll also try to see why the redshift tests are failing on python3.3.

**Comment by Tarrasch** [comment]
This is an awesome catch. Please squash and give description and I'll merge! :)

**Comment by gpoulin** [comment]
@Tarrasch Done! Travis should be red because of an issue in the redshift test on python3. I'll try to fix later. There is also some error at the shutdown of the test https://travis-ci.org/spotify/luigi/jobs/51953774#L736. It seems to be due to worker that stay alive after the tests and try to acquire a lock that is deleted before the worker. Not sure thou.

**Comment by Tarrasch** [comment]
Thank you so much!!!! :)

**Pull request merged**
