### PR TITLE
Retries get_work on null response

### PR DESCRIPTION
**Pull request by daveFNbuck**
Sometimes the scheduler gives a null response to get_work, resulting in an error
when the worker tries to treat the response as a dict and killing the worker.
This change will retry up to 3 times upon receiving a null response, allowing
the worker to live and continue working.

Note: this has a merge conflict with #1341 because they both modify get_work but it's easily resolved.

### CODE REVIEW

**Comment by daveFNbuck** [comment]
Note: this has been happening to me about 4 times a day since recently moving my scheduler to a different server from my workers.

**Comment by erikbern** [comment]
LGTM but why does the scheduler return a null result? That sounds like the underlying issue

**Comment by daveFNbuck** [comment]
I have no idea how that happens or whether it's a network issue or a scheduler issue. I don't think my logs go back far enough to check.

**Comment by erikbern** [comment]
oops seems like there's a merge conflict here. any chance you can rebase?

**Comment by daveFNbuck** [comment]
Done. Thanks for all the merges today!

**Pull request merged**
