### PR TITLE
Use the minicluster for Hadoop mapreduce jobs

### PR DESCRIPTION
**Pull request by erikbern**
Seems pretty useful for testing: http://hadoop.apache.org/docs/r2.5.1/hadoop-project-dist/hadoop-common/CLIMiniCluster.html

### CODE REVIEW

**Comment by erikbern** [comment]
Some more notes:
- No functionality in luigi is changed, just in the tests
- I deleted a lot of old tests that mocked out popen etc because the code paths should now be tested
- `unicode_job` is failing on the mini cluster. I disabled it for now. We should figure out what's the issue. Note that we never had that test for this before
- It might be worth to promote some of this code into luigi so that it can be used by people who want to test their Hadoop pipelines

**Comment by anyman** [comment]
Looks great.

Nice with the refactoring breaking out minicluster test. This should be applied to snakebite_test as well.

**Comment by Tarrasch** [comment]
LGTM. I merge since +2 and I might need these changes.

**Comment by erikbern** [comment]
Great!

Why do you need these changes?

**Comment by Tarrasch** [comment]
Thought of making changes to the snakebite client. And maybe will refactor those tests at the same time.

**Comment by erikbern** [comment]
Ok, got it. Maybe we should move the minicluster functionality into its own repo?

**Comment by erikbern** [comment]
Btw I might try to add integration tests for Scalding, depending on how messy it is

**Pull request merged**
