### PR TITLE
added copyright headers to some files

### PR DESCRIPTION
**Pull request by erikbern**

### CODE REVIEW

**Comment by Tarrasch** [comment]
Shouldn't it be 2016? :)

What ever. Looks fine to merge to me.

**Comment by erikbern** [comment]
not sure if we should update all the other files too

**Comment by Tarrasch** [comment]
I think the commit message "2015-2016" is too confusing to make this PR merge-able. Can you squash the commits instead?

**Comment by erikbern** [comment]
just did it

but i really think we should be more lax about rebasing. it's not that big of a deal

**Comment by Tarrasch** [comment]
Thanks for doing it. :)

It's a difficult topic with many pros and cons. I really just wished GitHub would let me squash commits in the web UI in a convenient quick way ...

**Pull request merged**
