### PR TITLE
Remove TravisCI and group similar steps 

### PR DESCRIPTION
**Pull request by ckiosidis**
## Description

Removing .travis.yaml.

Also groupped the jobs based on the steps.
Kept core separate because it uses mysql DB.
Added a postgres for the postgres tests.
Kept the rest in one job because they don't do anything special 

## Motivation and Context

Moving away from Travis CI https://github.com/spotify/luigi/issues/3016

### CODE REVIEW

**Review by tnsetting — DISMISSED** [review]

**Comment by honnix** [comment]
Nice. Please remember to configure branch protection rules to enforce GitHub Actions and remove Travis: https://github.com/spotify/luigi/settings/branch_protection_rules/155515

**Comment by ckiosidis** [comment]
Ah yes! Followed some steps on this guide https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule  and: 

```
- Enabled `Require pull request reviews before merging`
      - Enabled `Dismiss stale pull request approvals when new commits are pushed`
- Require status checks to pass before merging (was already enabled)
      - Enabled `Require branches to be up to date before merging`
      - Selected the final combination of all the actions (base, core, postgres)
```


I believe that this should be fine. What do you think @honnix

**Comment by honnix** [comment]
Please enabled all the status checks as well except Travis:

Screenshot 2021-04-09 at 11 19 50

**Comment by ckiosidis** [comment]
The steps you linked run in a previous build but were refactored out from the "final" CI file.
base (pyXX-aws) and base(pyXX-azureblob) should be these actions

**Comment by honnix** [comment]
I think we should enable all checks.

**Comment by ckiosidis** [comment]
Yes all 29 checks that are run in the build are Required 👍 
- 3 codecov
- 1 flake
- 1 docs
- 4 core
- 4 postgres
- 4 aws
- 4 azure
- 4 apache
- 4 unixsocket

**Comment by ckiosidis** [comment]
Codecov integration with Github Actions is missing.
I disabled the required steps and solving this on the next PR.

**Review by tnsetting — APPROVED** [review]

**Pull request merged**
