### PR TITLE
Py3k unit test

### PR DESCRIPTION
**Pull request by gpoulin**
some test fix for python3. I suggest that we merge this only when all non-hdfs test pass for py3k.

### CODE REVIEW

**Comment by Tarrasch** [comment]
I like your suggestion! :)

**Comment by gpoulin** [comment]
I'll try to find sometime today to fix the module in contrib that conflict with the docs building.

Any idea on why Travis crashes on python 3.4? On my computer everything run smoothly. Only issue that I have are with test that required snakebite. I looked at the code and really don't understand how this traceback can occur.

**Comment by gpoulin** [comment]
The issue with the python3.4 seems to be due to tox environment. It run fine when running directly nosetest from my system environment but I get the same issue as Travis when running from tox. I'm not so familiar with tox but I'll try to figure out the issue. Is there a reason why python-daemon not part of the tox environment?

**Comment by erikbern** [comment]
Looking at the Travis output it seems like it's an issue in `luigi.contrib.ftp`

https://travis-ci.org/spotify/luigi/jobs/50870719

I guess we aren't running any unit tests for it

```
Warning, treated as error:
/home/travis/build/spotify/luigi/doc/api/luigi.contrib.rst:18: WARNING: autodoc: failed to import module 'luigi.contrib.ftp'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/build/spotify/luigi/.tox/docs/lib/python3.3/site-packages/sphinx/ext/autodoc.py", line 378, in import_object
    __import__(self.modname)
  File "/home/travis/build/spotify/luigi/luigi/contrib/ftp.py", line 180, in <module>
    class AtomicFtpfile(file):
NameError: name 'file' is not defined
```

**Comment by gpoulin** [comment]
The docs is failing because of the `contrib.ftp` module, I didn't have time to look at it yet. What I was more concerned about is Travis crashing when starting tornado server on python3.4. I turn out to be a bug in a dependency of spulec/moto#308. The nonhdfs test should pass now. Will fix the docs this week.

**Comment by Tarrasch** [comment]
Should I merge?

**Pull request merged**
