### PR TITLE
add Weebly to list of Luigi users

### PR DESCRIPTION
**Pull request by jasonmay**
## Description
Addition to documentation

## Motivation and Context
This solves the issue that Weebly is a cool company but people don't know they use Luigi.

## Have you tested this? If so, how?
I clicked 'Preview' and it looked fine.

### CODE REVIEW

**Comment by dlstadther** [comment]
Do you have any blog or PR post about Weebly's use of Luigi? I believe the preference is to link to useful applications of Luigi, more so than company homepages.

**Comment by jasonmay** [comment]
We don't have any posts at the moment, if that's a requirement, I'd be happy to discuss with my team about publishing something.

**Comment by dlstadther** [comment]
I'm not sure it's a requirement, but it's preferred. In general, it would be awesome to see more luigi blog posts out there though!

**Comment by erikbern** [comment]
yes would prefer to link to something!

**Comment by erikbern** [comment]
wonder if we should drop the requirement a bit and link to anyone that uses luigi, presentation or not.

**Comment by Tarrasch** [comment]
Not sure. [Airflow](https://github.com/apache/incubator-airflow#who-uses-airflow) have that kind of list, it's surely a lot bigger, but I'm not sure if it's providing value. I maybe prefer Luigi's list, as sometimes linked presentations are useful, but sometimes it's just links to websites or other repositories, so the quality and consistency is a bit low right now...

**Comment by dlstadther** [comment]
@Tarrasch & @erikbern ,

I think this depends on the image we're trying to convey here. If we just want to show that a lot of companies are/have using/used Luigi, then we go the Airflow route and accept links to homepages. However, if the goal is to provide interesting use cases/implementations of luigi then we go the latter.

As @Tarrasch noted, we currently have some of both. So perhaps we split the middle and accept links to homepages, but add references to blogs after the company name. Something like the following:

[Spotify](https://www.spotify.com) ([presentation](https://www.slideshare.net/erikbern/luigi-presentation-nyc-data-science))
[Schibsted](http://www.schibsted.com/)
[Example Company](#) ([presentation](#)) ([blog](#))

If we agree on this, i'm happy to submit the PR to modify the current README for this change.

**Comment by erikbern** [comment]
yeah i like @dlstadther's idea. i was thinking along the same lines. i would also put all companies with presentations or blog posts above the companies without

**Comment by erikbern** [comment]
can you rebase on latest changes now? thanks!

**Comment by dlstadther** [comment]
@jasonmay Please rebase on the latest changes. We'd be happy to merge your company into our list! Thanks!

**Comment by jasonmay** [comment]
It's rebased now; thanks for reviewing!

**Comment by dlstadther** [comment]
Thanks @jasonmay !

**Pull request merged**
