### PR TITLE
Add pep8 and autopep8 targets to tox

### PR DESCRIPTION
**Pull request by themalkolm**
Add handy tox targets to check against simplest pep8 check and automatically
correct them using autopep8.

Note that both pep8 and autopep8 could be run in more aggressive modes but
for the first time I leave them in the 'easy' mode.

```
$ tox -e pep8 | wc -l
425
$ tox -e autopep8
$ tox -e pep8 | wc -l
45
```

I leave the exercise to run autopep8 and observe changes for core developers.
The best part is you make one step towards a repo with a single code style.
One style - easier to read the code, right?

How cool is that? No more questions about code style ever - you just conform
to pep8.

### CODE REVIEW

**Comment by Tarrasch** [comment]
Awesome! LGTM!

**Comment by erikbern** [comment]
How does this work? When I submit a violating line of code, where does it complain?

**Comment by themalkolm** [comment]
No, this won't complain anywhere. This is a standalone targets for tox. So you could play with it for a while.

Later, when repo is pep8 conformant to the desired level you can enable 'tox -e pep8' check in travis to make sure that no pull request is merged that violates pep8. I can help with this later as well.

Is it sensible?

**Comment by Tarrasch** [comment]
It doesn't interact with github at all afaict. It's just locally. You can run tox with `-e pep8` now to get a count on the violations.

**Comment by Tarrasch** [comment]
Damn. You were one second ahead of me! @themalkolm :)

**Comment by erikbern** [comment]
Ok and for now the output of tox will be available if you go to Travis and look at the build logs?

**Comment by themalkolm** [comment]
@erikbern No, pep8 and autopep8 are not listed in `envlist` so they are not run by default.

> No, this won't complain anywhere. This is a standalone targets for tox. So you could play with it for a while.

**Comment by themalkolm** [comment]
I can fix everything, just think if you want to go this way to force code style for every pull request.

**Comment by Tarrasch** [comment]
Yea as this only affects local devlopment I think this makes sense and can be merged. But isn't there a way to get the actual pep8 violations instead of just the count?

**Comment by themalkolm** [comment]
@Tarrasch Sure, note that I *count* them explicitly. Do not count and you get all violations.

> tox -e pep8 | wc -l

**Comment by Tarrasch** [comment]
Ah I'm such an idiot. Look very good then. I'll let @erikbern pull the trigger.

**Comment by themalkolm** [comment]
@Tarrasch nah, here is the updated version. Here we add target, fix all issues and ask travis to always check for pep8 style. Should work.

autopep8 could be either run manually or we can make a git hook to always check for style on commit for changed files.

**Comment by themalkolm** [comment]
I encourage you to read the whole diff.

**Comment by Tarrasch** [comment]
Wow. interesting. I think this might be worth merging. I can live with the merge failures I suppose. :)

I did a quick scroll. Looks good.

**Comment by themalkolm** [comment]
Travis approves!

like-a-boss

**Comment by themalkolm** [comment]
coveralls commenting is annoying though

**Pull request merged**
