### PR TITLE
snakebite removed

### PR DESCRIPTION
**Pull request by drowoseque**
## Description
Snakebite HDFS client removed

## Motivation and Context
luigi.contrib.hdfs.snakebite_client removed as it does not support python 3 (https://github.com/spotify/snakebite)
#2831
## Have you tested this? If so, how?
Tests still passing

### CODE REVIEW

**Comment by honnix** [comment]
I think we will need to merge this PR after py2 dies.

**Comment by honnix** [comment]
I use `Python2 deprecation` label to track this kind of breaking changes. Sounds OK? @drowoseque

**Comment by drowoseque** [comment]
> I use `Python2 deprecation` label to track this kind of breaking changes. Sounds OK? @drowoseque

I think it's worth to create a separate branch for py2-deprecation  and merge PRs in it gradually

**Comment by honnix** [comment]
Yeah makes sense. We should do regular rebase from master though to minimise merge conflict. I created the branch, you can change the target branch of this and follow up PRs.

**Comment by drowoseque** [comment]
@honnix 
done

**Comment by drowoseque** [comment]
@honnix 
@dlstadther 
could pls take a look at this pr and if that's okay, we can merge it into `py2-deprecation` branch

**Comment by dlstadther** [comment]
I've never worked with the hadoop/hdfs side of luigi. The code removals make sense. The hadoop tests are included in the apache attr and the minicluster attr. Minicluster tests don't run in Travis and are being removed here, so that's fine. So lgtm given other approvals.

**Comment by drowoseque** [comment]
@thunderock 
@helkhalfi 
you seem to be the latest contributors to  `luigi.contrib.snakebite`
PTAL

**Pull request merged**
