### PR TITLE
More stronger random tmp filenames.

### PR DESCRIPTION
**Pull request by peykar**
It's better to have more stronger random tmp filenames, so duplication chance will be decreased.

### CODE REVIEW

**Comment by honnix** [comment]
Thanks for the PR. Have you encountered duplication in practice?

**Comment by peykar** [comment]
> Thanks for the PR. Have you encountered duplication in practice?

You're welcome. Nope, not really.

**Comment by peykar** [comment]
> I think there's a risk we're causing "too long file name" or broken cleanup-regexps for our users. I however don't think our users have any issue with duplicate names currently. Hmm...

Is there any test to check the aforementioned risk?

**Comment by honnix** [comment]
I would prefer we don't make this change if nothing currently known as broken, due to the risk @Tarrasch mentioned. And it is probably not worth the effort trying to mitigate the risk.

**Comment by peykar** [comment]
> I would prefer we don't make this change if nothing currently known as broken, due to the risk @Tarrasch mentioned. And it is probably not worth the effort trying to mitigate the risk.

ok

**Pull request closed without merging**
