### PR TITLE
Added support for SFTP.

### PR DESCRIPTION
**Pull request by dlstadther**
SFTP support has been requested for a few months, but no one got around to submitting a PR. Most SFTP code was taken from [drj42's gist](https://gist.github.com/drj42/a6da7d6d503a97fc3eef). This (testless) PR adds SFTP support using pysftp.

FTP still works as it did previously.

I did not separate FTP and SFTP into separate files for the convenience of just adding one additional (optional) parameter to the constructor to go from FTP to SFTP.

### CODE REVIEW

**Comment by erikbern** [comment]
lgtm

would love to see integration tests for the ftp code (there's a few ftp servers in python that we could spin up) but that's not blocking

**Comment by Tarrasch** [comment]
Yea  this contrib module surely needs a little bit love. I'm fine with merging if @dlstadther can just say that "I've at least tested it myself and it works for me".

**Comment by dlstadther** [comment]
I agree that ftp.py needs a bit more love. I presently don't have the time to spend on this module. I needed sftp support (as well as ftp) and since I made it happen (although not the best implementation), I thought I would submit as others may need this package.

@Tarrasch I can say that I put and get using ftp and sftp (using this PR) on a daily basis and it works for me.

**Comment by Tarrasch** [comment]
Thanks. :)

**Pull request merged**
