### PR TITLE
New  who uses in Update README.rst

### PR DESCRIPTION
**Pull request by joseEnrique**

### CODE REVIEW

**Comment by dlstadther** [comment]
I believe the preference is to link to presentation(s) your company has written showcasing your use of luigi as a means of showing the brevity of luigi's uses.

**Comment by erikbern** [comment]
Yes please share a link to a presentation or something like that if you can

**Comment by erikbern** [comment]
can you rebase on latest changes now? thanks!

**Comment by dlstadther** [comment]
Closing due to non-response and merge conflict

**Pull request closed without merging**
