### PR TITLE
Fix new flake8 tests

### PR DESCRIPTION
**Pull request by dlstadther**
## Description

Update flake8 compliance

## Motivation and Context

Flake8 started linting against stricter standards. This patch fixes the new ones.

* E722 - bare except
* E741 - ambiguous variable name
* E742 - ambiguous class definition

## Have you tested this? If so, how?
 

Travis will run.

### CODE REVIEW

**Comment by dlstadther** [comment]
Added test exclusions to wrong tox line :/

**Comment by daveFNbuck** [comment]
Why are these ones excessive? E741 and E742 only catch three test cases where we use l and I as class and variable names. For the bare except, I see a couple we can fix but the rest can just get around it by catching BaseException. There are only 13 instances of bare excepts in the repo, so it's still a quick fix. Note that if we had this enabled, it would have caught the latest docker commit, which has a bare except where it should be catching an `AttributeError`.

The reason your commit fails is that you modified the wrong line. The line you modified only runs flake8 on the docs. The line above is the one that runs it on everything else.

**Comment by dlstadther** [comment]
@daveFNbuck I've taken your guidance and fixed the current flake8 failures. I didn't spend the time to really determine what the `except` clauses should be catching except for the docker `AttributeError`.

**Comment by daveFNbuck** [comment]
I think most of them were meant to catch arbitrary exceptions, so that's fine. The redshift one should probably just be removed. No point in catching an exception just to re-raise it.

**Comment by dlstadther** [comment]
@daveFNbuck Good for me to merge?

**Comment by daveFNbuck** [comment]
LGTM

**Pull request merged**
