### PR TITLE
Remove redundant swap logic

### PR DESCRIPTION
**Pull request by DeaconDesperado**
This logic should no longer be necessary:  It was a result of some problems we were having with ingestion on the bigquery connector that have now be verified to work.

@Tarrasch sorry for the delay with this but should be all set now :)

### CODE REVIEW

**Comment by erikbern** [comment]
Is it still atomic?

**Comment by DeaconDesperado** [comment]
@erikbern [Thankfully, it is!](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.copy.writeDisposition)  The problem we were seeing was in unrelated java code that relied on partial loads per mapper in hadoop followed by a final table merge, so the intention here was to hide the table as it was loaded with disposition APPEND to avoid querying partial data.

The loads as performed by luigi via GCS are fully atomic.

**Comment by erikbern** [comment]
excellent

**Comment by Tarrasch** [comment]
Finally! Great job! :D

Just please amend the commits so the history looks clean. :)

**Comment by DeaconDesperado** [comment]
@Tarrasch Rebased

**Comment by Tarrasch** [comment]
Cool. Lets merge once tests pass! :)

**Comment by mbruggmann** [comment]
:+1: Also triggered a rebuild, tests are green now.

**Pull request merged**
