### PR TITLE
Login to docker hub

### PR DESCRIPTION
**Pull request by honnix**
## Description

Login to docker hub before pulling docker image.

## Motivation and Context

Anonymous access has been rate limited and that is impacting Luigi CI. This PR follows https://blog.travis-ci.com/docker-rate-limits to get it fixed.

Please note that `DOCKERHUB_TOKEN` is not yet created and will be done shortly.

### CODE REVIEW

**Comment by honnix** [comment]
This won't work for untrusted build though, I think.

**Comment by honnix** [comment]
@dlstadther PTAL. It is not easy to do for untrusted build (forked repo), so basically for trusted build we login to dockerhub, otherwise we take chance. The same token can be used later when we move to Github workflows.

**Review by dlstadther — APPROVED** [review]
Sorry for this massive delay; struggling to find time to spend on extracurricular dev projects...

---

These changes make sense according to the linked documentation from Travis

**Comment by honnix** [comment]
@dlstadther No worries. Thanks for taking a look and verifying.

**Pull request merged**
