### PR TITLE
fix landscape errors in luigi.contrib.pig

### PR DESCRIPTION
**Pull request by steenzout**
added missing sys import.
remove unnecessary import of datetime.
re-order 2nd sequence of imports.

### CODE REVIEW

**Comment by themalkolm** [comment]
Lets bring big guns! https://github.com/spotify/luigi/pull/712

:D

**Comment by steenzout** [comment]
@themalkolm :)
I just wasn't sure about the luigi import and if it should be done in a particular place so that logging is setup right before importing the logging module, etc but I guess you went one step further.

I remember reading (but can't find article) that sys and os, if needed, should always be the first 2 packages to be imported and in this order: sys and os.

**Comment by themalkolm** [comment]
@steenzout sounds like some magic trick this sys & os order

**Comment by erikbern** [comment]
i wonder if the import sorting will cause merge conflict for like everything now

**Comment by themalkolm** [comment]
@erikbern I want to be popular! Everybody now hates me!

**Comment by erikbern** [comment]
haha you're just optimizing for total delta line count :)

**Comment by steenzout** [comment]
I've rebased my changes with master.
local build, docs, PEP8 and nonhdfs looked good.
waiting for travis.

I've improved the commit message to a higher standard.

**Comment by Tarrasch** [comment]
Thanks!!

**Pull request merged**
