### PR TITLE
contrib.ecs: check the exit code

### PR DESCRIPTION
**Pull request by gregwebs**
@jfeala this is untested both in the production sense and the unit test sense. But I believe it is necessary.

### CODE REVIEW

**Comment by erikbern** [comment]
not sure whta this does but lgtm

**Comment by erikbern** [comment]
can you fix the flake8 issues?

**Comment by gregwebs** [comment]
I am not using this code. I am providing this as a benefit for @jfeala. Perhaps it should be a github issue instead? Feel free to close this.

**Comment by jfeala** [comment]
Thanks again, Greg. I'll add tests and submit a new PR soon, adding @gregwebs as author if possible. Ok to close

**Pull request closed without merging**
