### PR TITLE
Add support to IAM roles in AWS instances

### PR DESCRIPTION
**Pull request by eramirem**
The retrieval order for S3 credentials will be:
1. kwargs
2. luigi configuration
3. IAM role credentials via instance metadata

### CODE REVIEW

**Comment by deuxpi** [comment]
We are currently using the S3Target class with IAM roles by omitting the `aws_access_key_id` and `aws_secret_access_key` parameters. The only place where that doesn't quite work for now is when we're using the Redshift task classes, which require that the access key and the secret key be explicitly provided.

**Comment by erikbern** [comment]
looks good, can you rebase?

**Comment by eramirem** [comment]
I just checked and the IAM role is used indeed by just explicitly omitting key parameters. Should I close this?

**Comment by erikbern** [comment]
Sure if the PR doesn't add any functionality let's just close it. But thanks anyway

**Pull request closed without merging**
