### PR TITLE
don't use absolute path in redirect for visualizer

### PR DESCRIPTION
**Pull request by timkpaine**
In reverse proxy setups, you sometimes want to setup sites behind a sub path e.g. my.site.com/luigi/
This PR makes sure the initial redirect is relative to the base_url, not absolute.

### CODE REVIEW

**Comment by honnix** [comment]
Thanks for the PR. Have you tested this will work for both behind reverse proxy and direct access?

**Comment by timkpaine** [comment]
will get back to this this week, got distracted

**Comment by timkpaine** [comment]
@honnix works fine for both, @Tarrasch it might be possible to modify this test to test explicitly
https://github.com/spotify/luigi/blob/865cc4e97540b5adc19898cbb5f31f39bff791de/test/server_test.py#L101

**Comment by honnix** [comment]
Something like this would work https://github.com/tornadoweb/tornado/blob/master/tornado/test/httpclient_test.py#L293

**Comment by timkpaine** [comment]
some further activity

**Comment by timkpaine** [comment]
finally got around to this and added a test that specifically checks there is no leading slash:

```python
        response = self.fetch("/", follow_redirects=False)
        self.assertEqual(response.code, 302)
        self.assertEqual(response.headers['Location'], 'static/visualiser/index.html')  # assert that doesnt beging with leading slash !
```

**Comment by timkpaine** [comment]
thanks!

**Comment by tashrifbillah** [comment]
This work missed my eyes. I have reported the need in many places before including issue https://github.com/spotify/luigi/issues/2981. A similar issue is https://github.com/spotify/luigi/issues/2670. Thanks for the modification. I shall test it and let you know.

**Comment by tashrifbillah** [comment]
Unfortunately, the PR didn't work for me. See below a comparison between `plotly` server and `luigi` server:

# Launching luigid

> luigid --port 8083

# Confirming luigi is functional w/o proxy

> curl -L http://localhost:8083

# Configuring nginx proxy

```vim
    server {

        root /var/www/html/;


        location /luigi/ {
            proxy_pass http://localhost:8083;
        }

        location /dash/ {
            proxy_pass http://localhost:8084;
        }


    }

```


# Issue
```
# works gracefully
curl -L http://myIP/dash/

# fails :(
curl -L http://myIP/luigi/
```

Failure logs:

<details><summary>console log</summary>

```vim
<html><title>404: Not Found</title><body>404: Not Found</body></html>
```

</details>

<details><summary>nginx/access.log</summary>

```vim
170.223.221.217 - [13/Nov/2020:18:54:43 -0500] "GET /luigi/ HTTP/1.1" 404 69 "-" "curl/7.29.0" "-"
```

</details>

<details><summary>nginx/error.log</summary>

```vim
2020/11/13 19:05:09 [notice] 106027#0: signal process started
```

</details>

@timkpaine @honnix

**Comment by timkpaine** [comment]
The logs you posted are nginx telling you that the route is missing. Nothing to do with Luigi, you haven't even hit the Luigi process.

**Comment by timkpaine** [comment]
also you installed from master right?

**Comment by timkpaine** [comment]
don't you need a trailing slash on `proxy_pass http://localhost:8083;`? otherwise you're redirecting to localhost:8083/luigi/, where whereas this is a valid dash route, its not a valid luigi route

**Comment by tashrifbillah** [comment]
> also you installed from master right?

Upon release 3.0.2, I applied your change, which is just one `/` removal.

Can you see my edited comment above for `Tornado log`?

**Comment by timkpaine** [comment]
https://serverfault.com/questions/562756/how-to-remove-the-path-with-an-nginx-proxy-pass

**Comment by tashrifbillah** [comment]
Thanks Tim, it looks like the trailing slash is required. So is it the trailing slash that makes sure the redirection is towards `http://localhost:8083`?

That said, I am going to do a few more tests tonight with other tabs such as `/history`.

**Comment by timkpaine** [comment]
yeah all of this has nothing to do with luigi, its all nginx configuration. The trailing slash ensures that myip/luigi/a/path -> localhost:8083/a/path. You just happened to get unlucky with the url as dash directs its traffic through /dash anyway.

**Comment by tashrifbillah** [comment]
Hello again @timkpaine , unfortunately, we are not set yet. Have you tried to run a job through your modification? See the issue I figured:

### nginx.conf

```vim
    server {
        root /var/www/html/;
        location /luigi/ {
            proxy_pass http://localhost:8083;
        }
    }
```

### luigi.cfg:

```vim
[core]
default-scheduler-url = http://myIP/luigi/

[scheduler]
record_task_history = True
state_path = ${HOME}/luigi-state.pickle

[task_history]
db_connection = sqlite:///${HOME}/luigi-task-hist.db
```


### Error

Then if you try my [simple task](https://gist.github.com/tashrifbillah/2bca276c7a6e2d5c85e9206d6522b37e), it should run into the following error:

```vim
WARNING: Failed connecting to remote scheduler 'http://myIP/luigi'
Traceback (most recent call last):
  File "/tmp/new_luigi/miniconda3/lib/python3.7/site-packages/luigi/rpc.py", line 163, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/tmp/new_luigi/miniconda3/lib/python3.7/site-packages/luigi/rpc.py", line 117, in fetch
    resp.raise_for_status()
  File "/tmp/new_luigi/miniconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://myIP/api/add_task
```

As apparent from `http://myIP/api/add_task`, I think my nginx URL rewriting isn't right. `http://myIP/api/add_task` isn't even hitting Luigi. It should be `http://localhost:8083/api/add_task`.

Any suggestion about the URL rewriting for `@proxy_pass` in the above `nginx.conf`?

**Comment by timkpaine** [comment]
I don't use nginx for this but I think you'll have a lot easier time if you set it up as a sub domain rather than a path, e.g. luigi.myip rather than myip/luigi. When you reverse proxy under paths, often times you need a lot more library modifications.

**Comment by tashrifbillah** [comment]
Did you test the job scheduling part other than visualizer?

**Comment by timkpaine** [comment]
I run jobs from the same machine so my scheduler url is local host. But it's reasonable to assume that the client would still use absolute paths. This would still work fine with a sub domain instead of a path

**Comment by tashrifbillah** [comment]
I shall try what you suggested. More info for you--the `/history` tab in the seemingly functional visualizer is missing style sheets. Did you notice that?

**Comment by tashrifbillah** [comment]
Hi @timkpaine , could you at least check if style sheets load for you in the `/history` tab?

**Comment by tashrifbillah** [comment]
I solved the style sheet loading issue by another location block:

```vim    
    server {
        root /var/www/html/;
        location /luigi/ {
            proxy_pass http://localhost:8083/;
        }

        location /static/ {
            proxy_pass http://localhost:8083/static/;
        }

    }
```

It is a hack that does not make me so happy but it works.

**Pull request merged**
