### PR TITLE
Add Task.getinstance(), Task.instantiate(), and getinstances() methods.

### PR DESCRIPTION
**Pull request by keisuke-nakata**
## Description
Automatic instantiation for dependent tasks via `self.getinstance()` instead of `self.input()`.

## Motivation and Context

When tasks are reused many times, I need to write same instantiation codes in `Task.run()`.
For example, if a task `MyTask` whose output is a csv is reused many times, I need to write same instantiation codes in its child tasks as:
```python
class ChildTask1(luigi.Task):
    def requires(self):
        return MyTask()
    def output(self):
        pass
    def run(self):
        ### this instantiation is redundant
        with self.input().open('r') as infile:
            reader = csv.reader(infile)
            indata = [row for row in reader]
        # do stuff

class ChildTask2(luigi.Task):
    def requires(self):
        return MyTask()
    def output(self):
        pass
    def run(self):
        ### this instantiation is redundant
        with self.input().open('r') as infile:
            reader = csv.reader(infile)
            indata = [row for row in reader]
        # do another stuff
```
Instead above, I want to write it like:
```python
class MyTask(luigi.Task):
    def requires(self):
        ...
    def instantiate(self):
        with self.output().open() as outfile:
            reader = csv.reader(outfile)
            outdata = [row for row in reader]
        return outdata

class ChildTask3(luigi.Task):
    def requires(self):
        return MyTask()
    def output(self):
        pass
    def run(self):
        ### automatic instantiation
        indata = self.getinstance()  # get an instance of self.input instead of file pointer
        # do stuff
```

## Have you tested this? If so, how?
 

I ran my jobs with this code and it works for me.

### CODE REVIEW

**Comment by keisuke-nakata** [comment]
Because my coding skill (and English) is poor, this pull request should be rejected.
I just want to show my idea and hear some opinions about it.

**Comment by erikbern** [comment]
why can't this be solved using normal inheritance?

**Comment by keisuke-nakata** [comment]
@erikbern OK here is another implementation for my idea. How about this?
```python
def getinstances(struct):
    if isinstance(struct, luigi.Task):
        return struct.instantiate()
    elif isinstance(struct, dict):
        return {k: getinstances(v) for k, v in six.iteritems(struct)}
    else:
        # Remaining case: assume r is iterable...
        try:
            s = list(struct)
        except TypeError:
            raise Exception('Cannot map %s to Task/dict/list' % str(struct))
    return [getinstances(r) for r in s]

class MyParentTask(luigi.Task):
    def requires(self):...
    def output(self):...
    def run(self):...
    def instantiate(self):
        with self.output().open() as outfile:
            reader = csv.reader(outfile)
            outdata = [row for row in reader]
        return outdata

class MyChildTask(luigi.Task):
    def requires(self):
        return MyParentTask()
    def output(self):...
    def run(self):
        indata = getinstances(self.requires())
        ...
```
Does the method `getinstances()` have any chance to be merged into the source?

**Comment by erikbern** [comment]
i don't get why MyChildTask can't just inherit from MyParentTask?

**Comment by keisuke-nakata** [comment]
@erikbern Sorry I could not understand why MyChildTask can inherit from MyParentTask...
In my understanding, the class inheritance is different from luigi's Task dependency system.

My motivation is: In every `MyChildTask` which requires `MyParentTask`, I need to write the same code to map `MyParentTask`'s output (like csv file) to Python's object (like `list` of `list`s), because `MyChildTask.input()` just returns `target`s. If `MyParentTask` has a method for instantiating its own output for its children tasks, children tasks need not to consider how to map input file to object, because its parent task do it.

**Comment by erikbern** [comment]
yeah but why can't you put that stuff on a parent class and use inheritance to duplicate the functionality?

**Comment by keisuke-nakata** [comment]
I got it. I can implement my motivation as below. I'm sorry to trouble you.
```python
class DependentTask(luigi.Task):
     def requires(self):...
     def output(self):...
     def run(self):...
     def instantiate(self):
          with self.output().open() as outfile:
              reader = csv.reader(outfile)
              outdata = [row for row in reader]
          return outdata

class MyTask(luigi.Task):
    def requires(self):
        return DependentTask()
    def output(self):...
    def run(self):
        indata = self.requires().instantiate()  # instead of self.input().open()
        ...
```

**Comment by Tarrasch** [comment]
Thanks for your pull request @keisuke-nakata. :)

**Pull request closed without merging**
