### PR TITLE
Allow non-ascii character in CLI

### LINKED ISSUE #901: Exception when a command-line parametter contains a non-ascii character
Hey,

We've just upgraded to Luigi 1.1.2, and now we get an error when launching Tasks that have utf-8 characters on the parameters.  (using python 2.7.3)

Here's the stacktrace we get : 
```
Traceback (most recent call last):
  File "examples/top_artists.py", line 283, in <module>
    luigi.run()
  File "/home/jonas/.virtualenvs/website/local/lib/python2.7/site-packages/luigi/interface.py", line 434, in run
    return interface.run(tasks, worker_scheduler_factory, override_defaults=override_defaults)
  File "/home/jonas/.virtualenvs/website/local/lib/python2.7/site-packages/luigi/interface.py", line 165, in run
    not(lock.acquire_for(env_params.lock_pid_dir, env_params.lock_size))):
  File "/home/jonas/.virtualenvs/website/local/lib/python2.7/site-packages/luigi/lock.py", line 59, in acquire_for
    my_pid, my_cmd, pid_file = get_info(pid_dir)
  File "/home/jonas/.virtualenvs/website/local/lib/python2.7/site-packages/luigi/lock.py", line 44, in get_info
    pid_file = os.path.join(pid_dir, hashlib.md5(my_cmd.encode('utf8')).hexdigest()) + '.pid'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 97: ordinal not in range(128)
```

Here I've just added a `plop = luigi.Parameter()` to `AggregateArtists`, and called it with 
`python examples/top_artists.py AggregateArtists --local-scheduler --date-interval 2012-06 --plop à`

The error seems to come from the [Python3 refactoring](https://github.com/spotify/luigi/pull/745). Removing `.encode('utf8')` on [this line](https://github.com/spotify/luigi/blob/master/luigi/lock.py#L44) seems to solve the problem, but I guess it was added for a reason ^^.

Any ideas of how we could solve this on our side, other than removing the encode?  (I'll try to add a test for it later)

### PR DESCRIPTION
**Pull request by gpoulin**
Fix #901

### CODE REVIEW

**Comment by Tarrasch** [comment]
The error is unrelated right? LGTM.

**Comment by Tarrasch** [comment]
Also let me know if you know why we get the `HTTP Error 400: Bad Request` error.

https://travis-ci.org/spotify/luigi/jobs/59754118

**Comment by gpoulin** [comment]
The error is unrelated and I'm unable to reproduce it locally. This test fails relatively often when the server process is not created/killed correctly, but I wouldn't expect a 400.

**Comment by Tarrasch** [comment]
Oh, sorry, I forgot to merge this!

Thanks for the patch! :)

**Pull request merged**
